function WordX(wrd,pron,chn)
{
this.word=wrd;
this.pron=pron;
this.chinese=chn;

function toStr(){
	return this.word+" " +this.pron+" "+this.chinese;
}
}

all_words_x=[
 new WordX("what","[hwɔt] pron 什么"),
 new WordX("is","[iz] v 是"),
 new WordX("what's","[hwɔts] what is 的缩写形式"),
 new WordX("your","[juə] pron 你的,你们的"),
 new WordX("name","[neim] n 名字"),
 new WordX("my","[mai] pron 我的"),
 new WordX("I"," [ai] pron 我"),
 new WordX("am","[æm] v 是"),
 new WordX("I'm"," [aim]   I am 的缩写形式"),
 new WordX("in","[in] prep 在...里(内,上)"),
 new WordX("row","[rəu] n (一)排,(一)行"),
 new WordX("one","[wʌn] num 一"),
 new WordX("number","['nʌmbə] n 数字,号码"),
 new WordX("two","[tu:] num 二"),
 new WordX("too","[tu:] adv 也"),
 new WordX("three","[θri:] num 三"),
 new WordX("are","[ɑ:] v 是"),
 new WordX("you","[ju:] pron 你,你们"),
 new WordX("yes","[jes] adv 是"),
 new WordX("four","[fɔ:] num 四"),
 new WordX("five","[faiv] num 五"),
 new WordX("no","[nəu] adv & adj 不,不是"),
 new WordX("not","[nɔt] adv 不"),
 new WordX("hi","[hai] int 喂(问候或唤起注意)"),
 new WordX("class","[klɑ:s] n (学校里的)班级,年级"),
 new WordX("grade","[greid] n 年级"),
 new WordX("six","[siks] num 六"),
 new WordX("seven","['sevn] num 七"),
 new WordX("eight","[eit] num 八"),
 new WordX("nine","[nain] num 九"),
 new WordX("ten","[ten] num 十"),
 new WordX("zero","['ziərəu] num & n 零"),
 new WordX("plus","[plʌs]  prep  加,加上"),
 new WordX("it","[it] pron 它"),
 new WordX("It's","[its] it is 的缩写形式"),
 new WordX("how","[hau] adv (指程度)多少,怎样"),
 new WordX("old","[əuld] adj ...岁的,老的"),
 new WordX("eleven","[i'levn] num 十一"),
 new WordX("twelve","[twelv] num 十二"),
 new WordX("minus","['mainəs] prep减,减去"),
 new WordX("thirteen","['θə:ti:n] num 十三"),
 new WordX("fourteen","['fɔ:'ti:n] num 十四"),
 new WordX("fifteen","['fif'ti:n] num 十五"),
 new WordX("hello","[hə'ləu] int喂(问候或唤起注意)"),
 new WordX("please","[pli:z] int 请"),
 new WordX("can","[kæn] v.aux 能,可以,会"),
 new WordX("spell","[spel] v  拼写"),
 new WordX("that","[ðæt] pron 那,那个"),
 new WordX("secret","['si:krit] n 秘密"),
 new WordX("this","[ðis] pron 这,这个"),
 new WordX("in","[in] prep  用...(表达)"),
 new WordX("English","['iŋgliʃ] n & adj 英语,英国人"),
 new WordX("in","English [in'iŋgliʃ]  phr. 用英语(表达)"),
 new WordX("a","[ei] art  一(个,件...)"),
 new WordX("clock","[klɔk] n 钟"),
 new WordX("and","[ænd] conj 和,又,而"),
 new WordX("pencil-box","['penslbɔks] n 铅笔盒"),
 new WordX("an","[æn] art  一(个;件.)"),
 new WordX("pencil","['pensl] n 铅笔"),
 new WordX("ruler","['ru:lə] n 尺子"),
 new WordX("pen","[pen] n 钢笔"),
 new WordX("sharpener","['ʃɑ:pənə]n 卷笔刀"),
 new WordX("eraser","[i'reisə] n 橡皮擦"),
 new WordX("room","[ru:m] n 房间"),
 new WordX("book","[buk] n 书"),
 new WordX("map","[mæp] n 地图"),
 new WordX("desk","[desk] n 书桌"),
 new WordX("cup","[kʌp] n 杯子"),
 new WordX("bag","[bæg] n 书包"),
 new WordX("mouse","[maus]n 鼠,耗子,鼠标"),
 new WordX("bed","[bed] n 床"),
 new WordX("keyboard","['ki:bɔ:d] n 键盘"),
 new WordX("isn't","['iznt]   is not 的缩写形式"),
 new WordX("pear","[pɛə] n 梨"),
 new WordX("cake","[keik] n 蛋糕,饼,糕"),
 new WordX("banana","[bə'nɑ:nə] n 香蕉"),
 new WordX("apple","['æpl] n 苹果"),
 new WordX("orange","['ɔ:rindʒ] n 橙子,橘子"),
 new WordX("egg","[eg] n 蛋"),
 new WordX("bike","[baik] n 自行车"),
 new WordX("bus","[bʌs] n 公共汽车"),
 new WordX("car","[kɑ:] n 汽车,小汽车"),
 new WordX("jeep","[dʒi:p] n 吉普车"),
 new WordX("Chinese['tʃai'ni:z]adj中国的,中国人的；n"," 中国人,汉语"),
 new WordX("look","[luk] v  瞧,看"),
 new WordX("who","[hu:] pron 谁"),
 new WordX("she","[ʃi:] pron 她"),
 new WordX("he","[hi:] pron 他"),
 new WordX("bird","[bə:d] n 鸟"),
 new WordX("Its","[its] pron 它的"),
 new WordX("don't","[dəunt] do not 的缩写形式"),
 new WordX("know","[nəu] v  知道,懂得"),
 new WordX("think","[θiŋk] v  想,认为"),
 new WordX("Mr=mister","['mistə] n 先生(用于姓名前)"),
 new WordX("very","['veri] adv 很,非常"),
 new WordX("picture","['piktʃə] n 图画,照片"),
 new WordX("Mrs","['mɪsɪz]","n 夫人"),
 new WordX("boy","[bɔi]","n 男孩"),
 new WordX("girl","[gə:l]","n 女孩"),
 new WordX("woman","['wumən]","n 妇女,女人"),
 new WordX("man","[mæn]","n 男人,人"),
 new WordX("cat","[kæt]","n 猫"),
 new WordX("his","[hiz]","pron 他的"),
 new WordX("teacher","['ti:tʃə]","n 教师"),
 new WordX("her","[hə:]","pron 她的"),
 new WordX("everyone","['evriwʌn]","pron 每人,人人"),
 new WordX("here","[hiə]","adv 这里,这儿"),
 new WordX("today","[tə'dei]","adv & n 今天"),
 new WordX("at","[æt]","prep  在"),
 new WordX("school","[sku:l]","n 学校"),
 new WordX("at","school","  phr. 在学校"),
 new WordX("sorry","['sɔri]","adj 对不起,抱歉的"),
 new WordX("where","[hwɛə]","adv 在哪里"),
 new WordX("home","[həum]","n 家"),
 new WordX("at","home","  phr. 在家"),
 new WordX("How","are","you？   你(身体)好吗?"),
 new WordX("fine","[fain]","adj (身体)好的"),
 new WordX("thanks","[θæŋks]","n 谢谢(只用复数)"),
 new WordX("OK","adv (口语)好,对,不错,可以"),
 new WordX("thank","[θæŋk]","v  谢谢"),
 new WordX("goodbye","[,gud'bai]","int 再见,再会"),
 new WordX("bye","[bai]","int 再见"),
 new WordX("parrot","['pærət]","n 鹦鹉"),
 new WordX("sister","['sistə]","n 姐,妹"),
 new WordX("father","['fɑ:ðə]","n 父亲"),
 new WordX("mother","['mʌðə]","n 母亲"),
 new WordX("box","[bɔks]","n 盒子,箱子"),
 new WordX("excuse","[iks'kju:z]","v  原谅"),
 new WordX("me","[mi:]","pron 我"),
 new WordX("Here","you","are    给你"),
 new WordX("but","[bʌt]","conj 但是"),
 new WordX("these","[ði:z]","pron 这些"),
 new WordX("they","[ðei]","pron 他(她,它)们"),
 new WordX("good","[gud]","adj 好的"),
 new WordX("those","[ðəuz]","pron 那些"),
 new WordX("boat","[bəut]","n 船"),
 new WordX("hill","[hil]","n 小山"),
 new WordX("tree","[tri:]","n 树"),
 new WordX("their","[ðɛə]","pron 他们(她们,它们)的"),
 new WordX("much","[mʌtʃ]","adv 多,很,非常"),
 new WordX("very","much","  phr. 很,非常"),
 new WordX("all","[ɔ:l]","adv 都,完全"),
 new WordX("right","[rait]","adv & adj 对的,正确的"),
 new WordX("all","right","  phr. 好,行,不错"),
 new WordX("mum","[mʌm]","n (口语)妈妈"),
 new WordX("friend","[frend]","n 朋友"),
 new WordX("brother","['brʌðə]","n 兄,弟"),
 new WordX("nice","[nais]","adj 令人愉快的"),
 new WordX("to","[tu:]","prep  (表示方向)到,向 动词不定式符号"),
 new WordX("meet","[mi:t]","v  见面,会面,遇见"),
 new WordX("child","[tʃaild]","n 小孩"),
 new WordX("children","['tʃildrən]","n child的复数形式"),
 new WordX("welcome","['welkəm]","v  欢迎"),
 new WordX("our","['auə]","pron 我们的"),
 new WordX("come","[kʌm]","v  来"),
 new WordX("come","in","  phr. 进来,进入"),
 new WordX("morning","['mɔ:niŋ]","n 早晨,上午"),
 new WordX("class","[klɑ:s]","n 同一个班的学生"),
 new WordX("on","[ɔn]","prep  在,在...上"),
 new WordX("duty","['dju:ti]","n 职责,责任"),
 new WordX("on","duty","  phr. 值日"),
 new WordX("we","[wi:]","pron 我们"),
 new WordX("aren't","[ɑ:nt]","are not 的缩写形式"),
 new WordX("have","[hæv]","v  有"),
 new WordX("new","[nju:]","adj 新的"),
 new WordX("student","['stju:dənt]","n 学生"),
 new WordX("twin","[twin]","n 双胞胎之一"),
 new WordX("look","[luk]","v  看上去,显得"),
 new WordX("the","[ðə]","art  这(那)个,这(那)些"),
 new WordX("same","[seim]","adj 同样的,同一的"),
 new WordX("look","the","same   phr. 看起来很像"),
 new WordX("America","[ə'merikən]n","& adj美国人(的)"),
 new WordX("sit","[sit]","v  坐"),
 new WordX("down","[daun]","adv 向下"),
 new WordX("sit","down","  phr. 坐下"),
 new WordX("over","['əuvə]","adv 在那边,在另一边"),
 new WordX("there","[ðɛə]","adv 那里,那儿"),
 new WordX("over","there","  phr. 在那边"),
 new WordX("after","['ɑ:ftə]","prep 在...以后,在...后面"),
 new WordX("look","after","  phr. 照顾,照看"),
 new WordX("way","[wei]","n 路,道路"),
 new WordX("This","way,please.","  请走这边"),
 new WordX("put","[put]","v  放"),
 new WordX("coat","[kəut]","n 外套,上衣"),
 new WordX("them","[ðem]","pron 他(她,它)们"),
 new WordX("washroom","['wɔʃrum]","n 盥洗室,厕所"),
 new WordX("let","[let]","v  让"),
 new WordX("us","[ʌs]","pron 我们"),
 new WordX("let's","[lets]","let us 的缩写形式"),
 new WordX("go","[gəu]","v  去"),
 new WordX("Let's","go","   我们一起去"),
 new WordX("classmate","['klɑ:smeit]","n 同班同学"),
 new WordX("nice","[nais]","adj 好的,漂亮的"),
 new WordX("love","[lʌv]","v  爱,喜爱"),
 new WordX("No","['nʌmbə]","n number 的缩写形式"),
 new WordX("middle","['midl]","adj 中间的,中级的"),
 new WordX("middle","school","  n 中学"),
 new WordX("well","[wel]","int 喔,那么,好吧"),
 new WordX("fax","[fæks]","n 传真"),
 new WordX("phone","[fəun]","n 电话,电话机"),
 new WordX("ID","n 身份征"),
 new WordX("policeman","[pə'li:smən]","n 警察"),
 new WordX("ask","[ɑ:sk]","v  问"),
 new WordX("sir","[sə:]","n (用于尊称)先生,阁下"),
 new WordX("licence","['laisəns]","n 执照,许可证"),
 new WordX("look","at","  phr. 看,观看"),
 new WordX("dear","[diə]","int (表示惊讶等)哎呀"),
 new WordX("see","[si:]","v  看见,看到"),
 new WordX("I'll","[ail]","I will 的缩写形式"),
 new WordX("will","[wil]","v.aux 将,会,要"),
 new WordX("take","[teik]","v  拿到,带到"),
 new WordX("address","[ə'dres]","n 地址"),
 new WordX("age","[eidʒ]","n 年龄"),
 new WordX("glad","[glæd]","adj 高兴的,乐意的"),
 new WordX("forgot[fə'gɔt]","v"," (forget 的过去时)忘记"),
 new WordX("now","[nau]","adv 现在"),
 new WordX("China","['tʃainə]","n 中国"),
 new WordX("or","[ɔ:]","conj 或者,还是"),
 new WordX("work","[wə:k]","v & n 工作"),
 new WordX("goes","[gəuz]","go的单数第三人称现在时"),
 new WordX("family","['fæmili]","n 家,家庭"),
 new WordX("family","tree","  n 家谱"),
 new WordX("grandmother","['grænd,mʌðə]","n (外)祖母"),
 new WordX("grandfather","['grænd,fɑ:ðə]","n (外)祖父"),
 new WordX("grandpa","['grændpɑ:]","n (口语)爷爷,外公"),
 new WordX("dad","[dæd]","n (口语)爸爸,爹爹"),
 new WordX("wife","[waif]","n 妻子"),
 new WordX("husband","['hʌzbənd]","n 丈夫"),
 new WordX("daughter","['dɔ:tə]","n 女儿"),
 new WordX("son","[sʌn]","n 儿子"),
 new WordX("parent","['pɛərənt]","n 父(母)亲"),
 new WordX("parents","['pɛərənts]  n 父母亲,双亲"),
 new WordX("big","[big]","adj 大的"),
 new WordX("England","['iŋglənd]","n 英格兰"),
 new WordX("aunt","[ɑ:nt]","n 姨母,舅母,姑母,伯母,婶母"),
 new WordX("uncle","['ʌŋkl]","n 叔,伯,舅,姨父,姑父"),
 new WordX("afternoon","['ɑ:ftə'nu:n]","n 下午,午后"),
 new WordX("do","[du:]","v  做,干,行动"),
 new WordX("How","do","you do ?   你好!"),
 new WordX("seat","[si:t]","n 座位"),
 new WordX("have","a","seat    坐下,就坐"),
 new WordX("like","[laik]","prep  像,跟...一样"),
 new WordX("look","like"," phr. 看起来像"),
 new WordX("hat","[hæt]","n 帽子(一般指有边的帽子)"),
 new WordX("doctor","['dɔktə]","n 医生"),
 new WordX("worker","['wə:kə]","n 工人"),
 new WordX("guess","[ges]","v  猜"),
 new WordX("behind","[bi'haind]","prep 在...后面"),
 new WordX("chair[tʃɛə]","n"," 椅子"),
 new WordX("ball","[bɔ:l]","n 球"),
 new WordX("under","['ʌndə]","prep  在...下面"),
 new WordX("floor","[flɔ:]","n (室内)地,地板"),
 new WordX("can't","[kænt]","can not 的缩写形式"),
 new WordX("photo","['fəutəu]","n 照片"),
 new WordX("wall","[wɔ:l]","n 墙"),
 new WordX("shoe","[ʃu:]","n 鞋"),
 new WordX("near","[niə]","prep 在...附近"),
 new WordX("door","[dɔ:]","n 门"),
 new WordX("of","[ɔv]","prep  ...的"),
 new WordX("classroom","['klɑ:srum]","n 教室"),
 new WordX("answer","['ɑ:nsə]","v  回答"),
 new WordX("blackboard","['blækbɔ:d]","n 黑板"),
 new WordX("some","[sʌm]","pron 一些,若干"),
 new WordX("schoolbag","['sku:l,bæg]","n 书包"),
 new WordX("flower","['flauə]","n 花"),
 new WordX("find","[faind]","v  找到,发现"),
 new WordX("broom","[bru:m]","n 扫帚"),
 new WordX("window","['windəu]","n 窗"),
 new WordX("raincoat","['reinkəut]","n 雨衣"),
 new WordX("cap","[kæp]","n 便帽,军帽"),
 new WordX("football","['futbɔ:l]","n 足球"),
 new WordX("table","['teibl]","n 桌子"),
 new WordX("Hong","Kong","[ 'hɔŋ'kɔŋ ]n 香港"),
 new WordX("Macao","[mə'kau]","n 澳门"),
 new WordX("SAR","n 特别行政区"),
 new WordX("there's","[ðɛəz]","there is 的缩写形式"),
 new WordX("lock","[lɔk]","v& n 锁"),
 new WordX("many","['meni]","adj 许多的,多的"),
 new WordX("thing","[θiŋ]","n 东西,事情"),
 new WordX("must","[mʌst]","v.aux 必须,应当"),
 new WordX("open","['əupən]","v  打开"),
 new WordX("get","[get]","v  得到,获得"),
 new WordX("help","[help]","v  帮助"),
 new WordX("purse","[pə:s]","n 钱包"),
 new WordX("money","['mʌni]","n 钱,货币"),
 new WordX("worry","['wʌri]","v  (使)担忧"),
 new WordX("Let","me","see    让我想想"),
 new WordX("fifty","['fifti]","num 五十"),
 new WordX("colour","['kʌlə]","n 颜色"),
 new WordX("black","[blæk]","adj 黑色的"),
 new WordX("house","[haus]","n 房子"),
 new WordX("small","[smɔ:l]","adj 小的"),
 new WordX("playhouse","['pleihaus]","n 儿童游戏房"),
 new WordX("like","[laik]","v  喜欢"),
 new WordX("play","[plei]","v  玩,打(球)"),
 new WordX("up","[ʌp]","adv 在上面,在高处,向上,起来"),
 new WordX("with","[wið]","prep  和"),
 new WordX("great","[greit]","adv (口语)好极了,很好"),
 new WordX("look","[luk]","n 瞧,看"),
 new WordX("have","a","look   phr. 看一看"),
 new WordX("ping-pong","['","piŋpɔŋ] n 乒乓球"),
 new WordX("how","many","  phr. 多少"),
 new WordX("kite","[kait]","n 风筝"),
 new WordX("young","[jʌŋ]","adj 年轻的,幼小的"),
 new WordX("pioneer","[,paiə'niə]","n 先锋"),
 new WordX("Young","Pioneer","  n 少先队员"),
 new WordX("men","[men]","n   man的缩写形式"),
 new WordX("women","['wimin]","n   woman的复数形式"),
 new WordX("only","['əunli]","adv 仅仅,只"),
 new WordX("work","[wə:k]","n 工作"),
 new WordX("at","work","  phr. 在工作"),
 new WordX("sky","[skai]","n 天空"),
 new WordX("count","[kaunt]","v  数,点数"),
 new WordX("river","['rivə]","n 江,河"),
 new WordX("dog","[dɔg]","n 狗"),
 new WordX("light","[lait]","n 灯"),
 new WordX("animal","['æniməl]","n 动物"),
 new WordX("people","['pi:pl]","n 人,人们"),
 new WordX("little","['litl]","adj & adv 小的,一点儿,稍许"),
 new WordX("sheep","[ʃi:p]","n 绵羊"),
 new WordX("come","on","['kʌm ɔn]phr. 来吧,跟着来,赶快"),
 new WordX("red","[red]","adj & n 红色(的)"),
 new WordX("colour","['kʌlə]","n颜色；v 给...着色"),
 new WordX("yellow","['jeləu]","adj & n 黄色(的)"),
 new WordX("blue","[blu:]","adj & n 蓝色(的)"),
 new WordX("white","[hwait]","adj & n 白色(的)"),
 new WordX("green","[gri:n]","adj & n 绿色(的)"),
 new WordX("purple","['pə:pl]","adj & n 紫色(的)"),
 new WordX("brown","[braun]","adj&n棕色(的),褐色(的)"),
 new WordX("orange","['ɔ:rindʒ]","adj & n 橙色(的)"),
 new WordX("grey","[grei]","adj & n 灰色(的),灰白(的)"),
 new WordX("sweater","['swetə]","n 毛衣,厚运动衫"),
 new WordX("light","[lait]","adj 淡(浅)色的,轻的"),
 new WordX("want","[wɔnt]","v  要,想要"),
 new WordX("which","[hwitʃ]","pron & adj 哪一个,哪些"),
 new WordX("one","[wʌn]","pron 用来代替单数的人或物"),
 new WordX("clothes","[kləuðz]","n 衣服"),
 new WordX("line","[lain]","n 线,绳索"),
 new WordX("whose","[hu:z]","pron 谁的"),
 new WordX("blouse","[blauz]","n 女衬衫"),
 new WordX("dress","[dres]","n 女服,(统称)衣服"),
 new WordX("shirt","[ʃə:t]","n (男式)衬衫"),
 new WordX("trousers","['trauzəz]","n 裤子"),
 new WordX("skirt","[skə:t]","n 女裙"),
 new WordX("dark","[dɑ:k]","adj 深(浓)色的,黑暗的"),
 new WordX("yours","[juəz]","pron 你的,你们的"),
 new WordX("mine","[main]","pron 我的"),
 new WordX("hers","[hə:z]","pron 她的"),
 new WordX("put","on"," phr.穿上(衣服等),戴上(帽子等)"),
 new WordX("theirs","[ðɛəz]","pron他们(她们,它们)的"),
 new WordX("ours","['auəz]","pron 我们的"),
 new WordX("glove","[glʌv]","n 手套"),
 new WordX("about","[ə'baut]","prep  关于,对于"),
 new WordX("What","about...?"," phr. (询问消息,征求意 见)…怎么样?"),
 new WordX("beside","[bi'said]","prep 在...旁边"),
 new WordX("watch","[wɔtʃ]","n & v  手表、观看,注视"),
 new WordX("give","[giv]","v  给"),
 new WordX("time","[taim]","n 时间"),
 new WordX("about","[ə'baut]","adv 大约"),
 new WordX("thirty","['θə:ti]","num 三十"),
 new WordX("get","up","['get ʌp] phr. 起床"),
 new WordX("late","[leit]","adj & adv 迟的(地),晚的(地)"),
 new WordX("o'clock","[ə'klɔk]"," …点钟"),
 new WordX("midnight","['midnait]","n 午夜"),
 new WordX("noon","[nu:n]","n 中午,正午"),
 new WordX("past","[pɑ:st]","prep  (超)过,经过"),
 new WordX("half","[hɑ:f]","n 半,一半"),
 new WordX("quarter","['kwɔ:tə]","n 一刻钟,四分之一"),
 new WordX("for","[fɔ:]","prep  为,给"),
 new WordX("break","[breik]","n (课间)休息,中断"),
 new WordX("lunch","[lʌntʃ]","n 午餐"),
 new WordX("breakfast","['brekfəst]","n 早餐"),
 new WordX("clean","[kli:n]","v  把...弄干净,擦干净"),
 new WordX("supper","['sʌpə]","n 晚餐"),
 new WordX("have","supper","  phr. 吃晚餐"),
 new WordX("TV"," n 电视,电视机"),
 new WordX("watch","TV"," phr. 看电视"),
 new WordX("game","[geim]","n 游戏,运动"),
 new WordX("go","home","  phr. 回家"),
 new WordX("p.m."," 下午,午后"),
 new WordX("London","['lʌndən]","n 伦敦"),
 new WordX("Tokyo","['təukiəu]","n 东京"),
 new WordX("Sydney","['sidni]","n 悉尼"),
 new WordX("hour","[auə]","n 小时"),
 new WordX("a.m."," 午前,上午"),
 new WordX("hundred","['hʌndrəd]","num 百"),
 new WordX("yourself","[juə'self]","pron 你自己"),
 new WordX("bedroom","['bedrum]","n 卧室"),
 new WordX("doll","[dɔl]","n 玩具娃娃"),
 new WordX("else","[els]","adv & adj 别(的),其他(的)"),
 new WordX("sure","[ʃuə]adv&adj的确,一定","确信的,肯定的"),
 new WordX("between","[bi'twi:n]","prep在(两者)之间"),
 new WordX("tall","[tɔ:l]","adj 高的"),
 new WordX("funny","['fʌni]","adj 滑稽的,有趣的"),
 new WordX("favourite","['feivərit]","adj 特别喜爱的"),
 new WordX("e-mail","[i:'meil]","n 电子邮件"),
 new WordX("speak","[spi:k]","v  讲,说"),
 new WordX("next","['nekst]","adj 下一个"),
 new WordX("term","[tə:m]","n 学期"),
 new WordX("could","[kud]","v.aux (口语,表示许可或请求)可以,行"),
 new WordX("minute","['minit]","n 分钟,一会儿"),
 new WordX("Tuesday","['tju:zdi]","n 星期二"),
 new WordX("February","['februəri]","n 二月"),
 new WordX("eighteenth","['ei'ti:nθ]","num 第十八"),
 new WordX("listen","['lisn]","v  听"),
 new WordX("careful","['kɛəfəl]","adj 小心的;仔细的"),
 new WordX("carefully","['kɛəfəli]","adv 小心地;仔细地"),
 new WordX("draw","[drɔ:]","v  画;绘制"),
 new WordX("has","[hæz]","v(动词have的单数第三人称)有"),
 new WordX("face","[feis]","n 脸;面孔"),
 new WordX("eye","[ai]","n 眼睛"),
 new WordX("ear","[iə]","n 耳朵"),
 new WordX("leg","[leg]","n 腿"),
 new WordX("hand","[hænd]","n 手"),
 new WordX("long","[lɔŋ]","adj 长的"),
 new WordX("short","[ʃɔ:t]","adj 短的;矮的"),
 new WordX("mouth","[mauθ]","n 嘴"),
 new WordX("say","[sei]","v  说;讲"),
 new WordX("tick","[tik]","n (钟表等滴嗒的)声音"),
 new WordX("heavy","['hevi]","adj 重的"),
 new WordX("empty","['empti]","adj 空的"),
 new WordX("certainly","['sə:tənli]","adv 当然"),
 new WordX("full","[ful]","adj 满的"),
 new WordX("be","full","(of)  phr. 充满....的"),
 new WordX("carry","['kæri]","v  携带;搬运;运送"),
 new WordX("too","[tu:]","adv 太"),
 new WordX("so","[səu]","adv 这么;那么"),
 new WordX("listen","to","  phr. 听"),
 new WordX("tape","[teip]","n 磁带"),
 new WordX("there","[ðɛə]","int 好啦(表示安慰)"),
 new WordX("all","[ɔ:l]","adj 整个;所有的"),
 new WordX("basket","['bɑ:skit]","n 篮子"),
 new WordX("bottle","['bɔtl]","n 瓶"),
 new WordX("a","bottle","of   phr. 一瓶..."),
 new WordX("juice","[dʒu:s]","n (水果;蔬菜;肉等的)汁;水汁"),
 new WordX("head","[hed]","n 头;头部"),
 new WordX("nose","[nəuz]","n 鼻子"),
 new WordX("hair","[hɛə]","n 头发"),
 new WordX("arm","[ɑ:m]","n 手臂;胳膊"),
 new WordX("foot","[fut]","n 脚(pl.feet)"),
 new WordX("wardrobe","['wɔ:drəub]","n 衣柜"),
 new WordX("day","[dei]","n 日;天"),
 new WordX("from","[frɔm]","prep  从.....起"),
 new WordX("America","[ə'merikən]","n 美国"),
 new WordX("zoo","[zu:]","n 动物园"),
 new WordX("away","[ə'wei]","adv 离开"),
 new WordX("put","away"," phr. 把.....什么收起来(放好)"),
 new WordX("out","[aut]","adv 在外"),
 new WordX("come","out","  phr. 出来"),
 new WordX("sock","[sɔk]","n 短袜"),
 new WordX("other","['ʌðə]","adj 别的;其他的"),
 new WordX("wrong","[rɔ:ŋ]","adj 不正确的;错误的"),
 new WordX("broken","['brəukən]","adj 弄坏了的"),
 new WordX("so","[səu]","pron 这样;如此"),
 new WordX("catch","[kætʃ]","v  捉;抓住"),
 new WordX("get","down","  phr. 下来;落下"),
 new WordX("him","[him]","pron 他(宾格)"),
 new WordX("right","[rait]","adv 正好;恰好;正确"),
 new WordX("goodness","['gudnis]","n 善良;美德"),
 new WordX("plane","[plein]","n 飞机"),
 new WordX("with","[wið]","prep  对....;关于"),
 new WordX("mend","[mend]","v  修补;修理"),
 new WordX("knife","[naif]","n (pl.knives) 小刀"),
 new WordX("robot","['rəubɔt]","n 机器人"),
 new WordX("body","['bɔdi]","n 身体"),
 new WordX("lost","[lɔst]","adj 丢失的;丢去的"),
 new WordX("tell","[tel]","v  告诉;讲述"),
 new WordX("round","[raund]","adj 球形的 ;圆的"),
 new WordX("mummy","['mʌmi]","n (口语)妈妈"),
 new WordX("pleasure","['pleʒə]","n 愉快;高兴"),
 new WordX("food","[fu:d]","n 食物"),
 new WordX("drink","[driŋk]","n & v  饮料   喝"),
 new WordX("hungry","['hʌŋgri]","adj 饥饿的"),
 new WordX("thirsty","['θə:sti]","adj 口渴的"),
 new WordX("water","['wɔ:tə]","n & v  水;浇水"),
 new WordX("eat","[i:t]","v  吃"),
 new WordX("rice","[rais]","n 米饭;大米"),
 new WordX("bread","[bred]","n 面包"),
 new WordX("meat","[mi:t]","n 肉"),
 new WordX("tea","[ti:]","n 茶"),
 new WordX("milk","[milk]","n 牛奶"),
 new WordX("glass","[glɑ:s]","n 玻璃杯"),
 new WordX("a","glass","of   phr. 一(玻璃)杯"),
 new WordX("would","like"," phr.想要(语气婉转地表示请求等)"),
 new WordX("porridge","['pɔridʒ]","n 粥;稀饭"),
 new WordX("fish","[fiʃ]","n 鱼"),
 new WordX("dumpling","['dʌmpliŋ]","n 饺子"),
 new WordX("fruit","[fru:t]","n 水果"),
 new WordX("piece","[pi:s]","n 一张(片;张)"),
 new WordX("a","piece","of   phr. 一片(一张、块)"),
 new WordX("hamburger","['hæmbə:gə]","n 汉堡包"),
 new WordX("noodle","['nu:dl]","n 面条"),
 new WordX("potato","[pə'teitəu]","n pl.potatoes 马铃薯;土豆"),
 new WordX("chips","[tʃip]","n (口语)炸士豆儿条"),
 new WordX("coke","[kəuk]","n (口语)可口可乐"),
 new WordX("coffee","['kɔfi]","n 咖啡"),
 new WordX("madam","['mædəm]","n 夫人;女士"),
 new WordX("dear","[diə]","adj 亲爱的;可爱的"),
 new WordX("ice","[ais]","n 冰"),
 new WordX("cream","[kri:m]","n 奶油;乳脂"),
 new WordX("ice","cream","  n 冰淇淋"),
 new WordX("USA"," n 美国"),
 new WordX("different","['difərənt]","adj 不同的"),
 new WordX("vegetable","['vedʒitəbl]","n 蔬菜"),
 new WordX("sometimes","['sʌmtaimz]","adv 有时"),
 new WordX("sport","[spɔ:t]","n 运动"),
 new WordX("come","on","  phr. 来;过来"),
 new WordX("ouch","[autʃ]","int (突然感到病痛时发出的声音)啊呀"),
 new WordX("be","good","at   phr. 在...方面(学得,做得)好; 善于"),
 new WordX("basketball","['bæskitbɔ:l] n 蓝球"),
 new WordX("easy","['i:zi]","adj 容易的"),
 new WordX("pass","[pɑ:s]","v  传递"),
 new WordX("try","[trai]","v  试(做);设法;努力"),
 new WordX("yo-yo","['jəujəu]","n 溜溜球 (一种玩具)"),
 new WordX("go","[gəu]","n 尝试(做某事)"),
 new WordX("throw","[θrəu]","v  投,掷"),
 new WordX("hard","[hɑ:d]","adj 困难的"),
 new WordX("ride","[raid]","v  骑(自行车,马等)"),
 new WordX("swim","[swim]","v  游泳"),
 new WordX("skate","[skeit]","v  滑冰,溜冰"),
 new WordX("fly","[flai]","v  放(风筝,飞机模型等)"),
 new WordX("card","[kɑ:d]","n 纸牌,卡片"),
 new WordX("volleyball","['vɔli,bɔ:l]","n 排球"),
 new WordX("jump","[dʒʌmp]","v  跳"),
 new WordX("sing","[siŋ]","v  唱,唱歌"),
 new WordX("run","[rʌn]","v  跑"),
 new WordX("high","[hai]","adj & adv 高的(地)"),
 new WordX("then","[ðen]","adv 那么,然后"),
 new WordX("question","['kwestʃən]","n 问题"),
 new WordX("postal","['pəustəl]","adj 邮政的"),
 new WordX("code","[kəud]","n 密码,符号"),
 new WordX("ski","[ski:]","v  滑雪"),
 new WordX("tennis","['tenis]","n 网球(运动)"),
 new WordX("table","tennis","  n 乒乓球"),
 new WordX("roller-skating","['rəuləskeitiŋ]","n 滑旱冰"),
 new WordX("chess","[tʃes]","n 国际象棋"),
 new WordX("fan","[fæn]","n (口语，电影,运动等的)迷"),
 new WordX("player","['pleiə]","n 比赛者,选手"),
 new WordX("team","[ti:m]","n 队,组"),
 new WordX("every","['evri]","adj 每一,每个的"),
 new WordX("Friday","['fraidi]","n 星期五"),
 new WordX("make","[meik]","v  做,制作"),
 new WordX("make","the","bed   phr. 整理床铺"),
 new WordX("homework","['həumwə:k]","n 家庭作业"),
 new WordX("do","homework","  phr. 做作业"),
 new WordX("read","[ri:d]","n 读,阅读"),
 new WordX("write","[rait]","v  写"),
 new WordX("sleep","[sli:p]","v  睡,睡觉"),
 new WordX("look","for","['luk fər] phr. 寻找"),
 new WordX("cook","[kuk]","v & n 烹调,煮,烧 炊事员,厨师"),
 new WordX("talk","[tɔ:k]","v  说话,谈话"),
 new WordX("talk","with","['tɔ:k wið]phr. 和....交谈"),
 new WordX("open","['əupən]","n 打开"),
 new WordX("close","[kləuz]","v  关;闭"),
 new WordX("take","photos","  phr. 照象"),
 new WordX("wear","[wɛə]","v  穿"),
 new WordX("Sunday","['sʌndi]","n 星期日"),
 new WordX("park","[pɑ:k]","n 公园"),
 new WordX("toy","[tɔi]","n 玩具;玩物"),
 new WordX("lake","[leik]","n 湖"),
 new WordX("clear","[kliə]","adj清晰的;清楚的;明亮的"),
 new WordX("shop","[ʃɔp]","n 商店"),
 new WordX("closed","[kləuzd]","adj 关着的"),
 new WordX("day","[dei]","n 日,一天"),
 new WordX("Friday","['fraidi]","n 星期五"),
 new WordX("early","['ə:li]","adj & adv  早的(地)初期"),
 new WordX("supermarket","['sju:pə,mɑ:kit]","n 超级市场"),
 new WordX("Wednesday","['wenzdi]","n 星期三"),
 new WordX("may","[mei]","v.aux 可以;可能;也许"),
 new WordX("borrow","['bɔrəu]","v  借"),
 new WordX("from","[frɔm]","prep  从;从....起"),
 new WordX("Thursday","['θə:zdi]","n 星期四"),
 new WordX("week","[wi:k]","n 周;星期"),
 new WordX("Monday","['mʌndei]","n 星期一"),
 new WordX("Saturday","['sætədi]","n 星期六"),
 new WordX("Sunday","['sʌndi]","n 星期日"),
 new WordX("dictionary","['dikʃəneri]","n 字典;词典"),
 new WordX("back","[bæk]","adv 回(原处) ;向后"),
 new WordX("tomorrow","[tə'mɔ:rəu]n&adv","明天;在明天"),
 new WordX("CD","n 激光唱片(缩写词)"),
 new WordX("lot","[lɔt]","n 许多"),
 new WordX("a","lot","  phr. 非常"),
 new WordX("give...a","hand","  phr. 给予.....帮助"),
 new WordX("evening","['i:vniŋ]","n 傍晚;晚上"),
 new WordX("from…to…"," phr.  …从…到…"),
 new WordX("after","class","  phr. 课后"),
 new WordX("help...with"," phr. 帮助(某人)做(某事)"),
 new WordX("model","['mɔdl]","n 模型;模范 ;样式"),
 new WordX("park","[pɑ:k]","n 公园"),
 new WordX("rest","[rest]","n 休息"),
 new WordX("have","a","(good) rest   phr. 休息"),
 new WordX("maths","[mæθs]","n (英式拼法)数学"),
 new WordX("math","[mæθ]","n (美式拼法)数学"),
 new WordX("all","[ɔ:l]","adv 全体;全部"),
 new WordX("hard","[hɑ:d]","adv 努力"),
 new WordX("fun","[fʌn]","adj 有趣的;愉快的"),
 new WordX("yeah","[jɛə]","adv (口语)是的;嗯"),
 new WordX("take","[teik]","v  花费(时间)"),
 new WordX("straight","[streit]","adj 直的"),
 new WordX("use","[ju:z]","v  用;使用;应用"),
 new WordX("wheel","[hwi:l]","n 轮;机轮"),
 new WordX("into","['intu:]","prep  到.....里;向内"),
 new WordX("music","['mju:zik]","n 音乐;乐曲"),
 new WordX("boat","[bəut]","v  划船"),
 new WordX("lake","[leik]","n 湖"),
 new WordX("into","['intu:]","prep  到...里,向内"),
 new WordX("worried","['wʌrid]","adj 担心的,烦恼的"),
 new WordX("save","[seiv]","v  救,挽救,节省"),
 new WordX("ticket","['tikit]","n 票,券"),
 new WordX("New","York","['nju:leid] n 纽约"),
 new WordX("learn","[lə:n]","v  学,学习"),
 new WordX("learn...from","phr. 向...学习"),
 new WordX("meeting","['mi:tiŋ]","n 会,会议"),
 new WordX("bring","[briŋ]","v  带来,拿来"),
 new WordX("foreign","['fɔrin]","adj 外国的"),
 new WordX("difference","['difərəns]","n 不同,差异"),
 new WordX("each","[i:tʃ]","adv & pron 各自,各个"),
 new WordX("each","other","  pron 互相"),
 new WordX("talk","about","  phr. 谈论,交谈"),
 new WordX("USA"," n 美国"),
 new WordX("Australia","[ɔ:s'treiljə]","n 澳大利亚"),
 new WordX("Canada","['kænədə]","n 加拿大"),
 new WordX("UK","n 联合王国"),
 new WordX("Japan","[dʒə'pæn]","n 日本"),
 new WordX("America","[ə'merikə]","n 美国"),
 new WordX("a","little","  phr. 一点,少量"),
 new WordX("French","[frentʃ]","n 法语"),
 new WordX("great","[greit]","adj 伟大的,很大的,重要的"),
 new WordX("the","Great","Wall  n 长城"),
 new WordX("hotel","[həu'tel]","n 旅馆,饭馆"),
 new WordX("building","['bildiŋ]","n 建筑物"),
 new WordX("follow","['fɔləu]","v  跟随"),
 new WordX("call","[kɔ:l]","v&n 称呼,叫喊,打电话给 电话,通话"),
 new WordX("family","name","  n 姓"),
 new WordX("first","[fə:st]","num & adv 第一,首先,最初"),
 new WordX("postcard","['pəust,kɑ:d]","n 明信片"),
 new WordX("teach","[ti:tʃ]","v  教,教书"),
 new WordX("dinner","['dinə]","n 正餐,晚餐"),
 new WordX("soon","[su:n]","adv 不久,一会儿"),
 new WordX("stay","[stei]","v  停留(在某处)"),
 new WordX("high","school","  n 中学"),
 new WordX("Toronto","[tə'rɔntəu]","n 多伦多(加拿大港市)"),
 new WordX("schoolboy","['sku:lbɔi]","n (中小学的)男学生"),
 new WordX("country","['kʌntri]","n 国家"),
 new WordX("make","friends","  phr. 交朋友"),
 new WordX("France","[frɑ:ns]","n 法国"),
 new WordX("textbook","['tekstbuk]","n 课本"),
 new WordX("Australian","[ɔ:s'treiljən]adj","澳大利亚人"),
 new WordX("Canadian","[kə'neidiən]","n 加拿大人"),
 new WordX("city","['siti]","n 城市"),
 new WordX("foreigner","['fɔ:rinə]","n 外国人"),
 new WordX("visit","['vizit]","v  访问,参观,拜访"),
 new WordX("word","[wə:d]","n 词,单词"),
 new WordX("well","[wel]","adv 好"),
 new WordX("why","[hwai]","adv 为什么"),
 new WordX("English-speaking","adj 说英语的"),
 new WordX("letter","['letə]","n 信"),
 new WordX("hot","[hɔt]","adj 热的,辣的"),
 new WordX("hot","dog","  n 热狗(红肠面包)"),
 new WordX("not...at","all","  phr. 一点也不"),
 new WordX("different","['difərənt]","adj 不同的"),
 new WordX("kind","[kaind]","n 种,类"),
 new WordX("a","kind","of   phr. 一种,一类"),
 new WordX("every","['evri]","adj 每一的,每个的"),
 new WordX("meal","[mi:l]","n 一餐,一顿饭"),
 new WordX("noodle","['nu:dl]","n 面条"),
 new WordX("vegetable","['vedʒitəbl]","n 蔬菜"),
 new WordX("restaurant","['restərɔnt]","n 饭馆"),
 new WordX("often","['ɔ:fən]","adv 常常"),
 new WordX("potato","[pə'teitəu]","n 马铃薯,土豆"),
 new WordX("well","[wel]","adj & adv 好,(身体)健康"),
 new WordX("why","[hwai]","adv 为什么"),
 new WordX("because","[bi'kɔ:z]","conj 因为"),
 new WordX("housework","['hauswə:k]","n 家务劳动"),
 new WordX("machine","[mə'ʃi:n]","n 机器"),
 new WordX("again","[ə'gen]","adv 又,再"),
 new WordX("make","phone","calls   phr. 打电话"),
 new WordX("wash","[wɔʃ]","v  洗,漱洗"),
 new WordX("dish","[diʃ]","n 一道菜,盘,碟"),
 new WordX("electronic","[ilek'trɔnik]","adj 电子的"),
 new WordX("mail","[meil]","n 邮政,邮递"),
 new WordX("smoke","[sməuk]","v&n 吸烟,烟"),
 new WordX("fog","[fɔg]","n 雾"),
 new WordX("dance","[dɑ:ns]","v  跳舞"),
 new WordX("living","room","  n 起居室"),
 new WordX("dining","room","  n 餐厅"),
 new WordX("driver","['draivə]","n 司机,驾驶员"),
 new WordX("farmer","['fɑ:mə]","n 农民"),
 new WordX("soldier","['səuldʒə]","n 士兵,战士"),
 new WordX("businessman","['biznismæn]","n 商人"),
 new WordX("assistant","[ə'sistənt]","n 助手,助理"),
 new WordX("a","shop","assistant   phr. 售货员,店员"),
 new WordX("nurse","[nə:s]","n 护士"),
 new WordX("postman","['pəustmən]","n 邮递员"),
 new WordX("factory","['fæktəri]","n 工厂"),
 new WordX("station","['steiʃən]","n 车站,所,站"),
 new WordX("bus","station","  n 公共汽车站"),
 new WordX("hospital","['hɔspitl]"," n 医院"),
 new WordX("farm","[fɑ:m]","n 农场"),
 new WordX("post","[pəust]","n 邮政,邮寄,邮件"),
 new WordX("office","['ɔ:fis]","n 办公室"),
 new WordX("post","office","  n 邮局"),
 new WordX("study","['stʌdi]","v  学习,研究"),
 new WordX("party","['pɑ:ti]","n 聚会"),
 new WordX("friendly","['frendli]","adj 友好的"),
 new WordX("also","['ɔ:lsəu]","adv 也"),
 new WordX("medicine","['medisin]","n 内服药,医学"),
 new WordX("in","the","day   phr. 在白天"),
 new WordX("at","night","  phr. 在晚上,在夜里"),
 new WordX("make","money","  phr. 赚钱"),
 new WordX("weekend","['wi:k'end]","n 周末"),
 new WordX("job","[dʒɔb]","n 工作"),
 new WordX("writer","['raitə]","n 作家,作者"),
 new WordX("cleaner","['kli:nə]","n 清洁工"),
 new WordX("turn","[tə:n]","n (依次轮流的)顺序,轮流"),
 new WordX("grow","[grəu]","v  种植,生长"),
 new WordX("baker","['beikə]","n 面包师"),
 new WordX("artist","['ɑ:tist]","n 画家,艺术家"),
 new WordX("hobby","['hɔbi]","n 业余爱好"),
 new WordX("be","[bi:]","v  (am,is,are)是,成为"),
 new WordX("place","[pleis]","n 地点,地方"),
 new WordX("weekday","['wi:kdei]","n 工作日,平日(除星期六,日以外)"),
 new WordX("when","[hwen]","adv 什么时候,何时"),
 new WordX("leave","[li:v]","v  离去,出发"),
 new WordX("begin","[bi'gin]","v  开始,着手"),
 new WordX("have","sports","  phr. 进行体育活动"),
 new WordX("go","to","bed   phr. 睡觉"),
 new WordX("usually","['ju:ʒuəli]","adv 通常"),
 new WordX("right","now","  phr. 立刻,马上"),
 new WordX("sometimes","['sʌmtaimz]","adv 有时"),
 new WordX("take","off","  phr. 脱衣服"),
 new WordX("after","school","  phr. 放学后,下课后"),
 new WordX("get","to","  phr. 到达"),
 new WordX("do","morning","exercises   phr. 做早操"),
 new WordX("shopping","['ʃɔpiŋ]","n 买东西"),
 new WordX("go","shopping","  phr. (去)买东西"),
 new WordX("garden","['gɑ:dn]","n 花(果,菜)园"),
 new WordX("be","[bi:]","v  (am,is,are)是,成为"),
 new WordX("over","['əuvə]","adv 结束,完了"),
 new WordX("do","(some)","reading   phr. 朗读,阅读"),
 new WordX("living-room","n 起居室"),
 new WordX("walk","[wɔ:k]","v  走,步行,散步"),
 new WordX("news","[nju:z]","n 新闻,消息"),
 new WordX("match","[mætʃ]","n 比赛,竞赛"),
 new WordX("quickly","['kwikli]","adv 迅速"),
 new WordX("sun","[sʌn]","n 太阳"),
 new WordX("moon","[mu:n]","n 月亮"),
 new WordX("bridge","[bridʒ]","n 桥"),
 new WordX("train","[trein]","n 火车"),
 new WordX("ship","[ʃip]","n 船,轮船"),
 new WordX("on","foot","  phr. 走路,步行"),
 new WordX("holiday","['hɔlədi]","n 假日,假期"),
 new WordX("year","[jiə]","n 年"),
 new WordX("by","[bai]","prep  乘车(船等)"),
 new WordX("by","plane","  phr. 乘飞机"),
 new WordX("by","ship","  phr. 乘船"),
 new WordX("air","[ɛə]","n 天空,空气"),
 new WordX("by","air","  phr. 乘飞机"),
 new WordX("sea","[si:]","n 海,海洋"),
 new WordX("by","sea","  phr. 乘船"),
 new WordX("take","time","  phr. 花费(时间)"),
 new WordX("how","long","  phr. 多久"),
 new WordX("walk","[wɔ:k]","v  走,步行,散步"),
 new WordX("clean","[kli:n]","adj 干净的,清洁的"),
 new WordX("story","['stɔ:ri]","n 故事"),
 new WordX("far","[fɑ:]","adj & adv 远"),
 new WordX("problem","['prɔbləm]","n 问题,难题"),
 new WordX("earlier","['ə:liə]","adj & adv ( early的比较级)更早的(地)"),
 new WordX("ill","[il]","adj 病的,不健康的"),
 new WordX("tear","[tɛə]","n (常用复数)眼泪,泪珠"),
 new WordX("chicken","['tʃikin]","n 鸡,鸡肉"),
 new WordX("tofu","['təufu:]","n 豆腐"),
 new WordX("fridge","[fridʒ]","n 电冰箱"),
 new WordX("list","[list]","n 清单,一览表,名单,目录"),
 new WordX("shopping","list","  phr. 购物清单"),
 new WordX("buy","[bai]","v  买"),
 new WordX("kilo","['ki:ləu]","n 千克,公斤"),
 new WordX("sell","[sel]","v  卖,售"),
 new WordX("how","much","  phr. 多少,多少钱"),
 new WordX("cheap","[tʃi:p]","adj 便宜的"),
 new WordX("expensive","[iks'pensiv]","adj 昂贵的"),
 new WordX("onion","['ʌnjən]","n 洋葱"),
 new WordX("carrot","['kærət]","n 胡萝卜"),
 new WordX("pork","[pɔ:k]","n 猪肉"),
 new WordX("all","day","  phr. 一整天,一天到晚"),
 new WordX("a","lot","of   phr. 许多,很多"),
 new WordX("open","['əupən]","adj 开着的"),
 new WordX("market","['mɑ:kit]","n 市场,集市"),
 new WordX("cent","[sent]","n (货币)分"),
 new WordX("pound","[paund]","n 镑(重量单位)"),
 new WordX("health","[helθ]","n 健康,卫生"),
 new WordX("fast","[fɑ:st]","adj & adv 快的(地),迅速的(地)"),
 new WordX("of","course","  phr. 当然,自然的事"),
 new WordX("travel","['trævl]","v & n 旅行"),
 new WordX("safe","[seif]","adj 安全的,平安的"),
 new WordX("minibus","['mini,bʌs]","n 小型公共汽车"),
 new WordX("and","so","on   phr. 等等"),
 new WordX("price","[prais]","n 价格,价钱"),
 new WordX("example","[ig'zɑ:mpl]","n 例子,榜样"),
 new WordX("for","example"," phr. 例如"),
 new WordX("stand","[stænd]","v  站,立"),
 new WordX("field","[fi:ld]","n 地,田地"),
 new WordX("one","day","phr.(过去或将来)有一天,某一天"),
 new WordX("job","[dʒɔb]","n 工作"),
 new WordX("bright","[brait]","adj 明亮的,灿烂的"),
 new WordX("foreign","['fɔrin]","adj 外国的"),
 new WordX("sunglasses","['sʌnglɑ:siz]","n 太阳镜"),
 new WordX("each","[i:tʃ]","pron 各自,各个"),
 new WordX("language","['læŋgwidʒ]","n 语言"),
 new WordX("helpful","['helpfəl]","adj 有帮助的,有益的"),
 new WordX("get","on","(a bus)  phr. 上车"),
 new WordX("business","['biznis]","n 商业,生意,事物"),
 new WordX("company","['kʌmpəni]","n 公司"),
 new WordX("manager","['mænidʒə]","n 经理,负责人"),
 new WordX("century","['sentʃuri]","n 世纪,百年"),
 new WordX("lesson","['lesn]","n 课,功课"),
 new WordX("fun","[fʌn]","n 有趣"),
 new WordX("when","[hwen]","conj 当......时"),
 new WordX("traffic","['træfik]","n 交通"),
 new WordX("bad","[bæd]","adj 坏的"),
 new WordX("on","time","  phr. 准时"),
 new WordX("September","[sep'tembə]","n 九月"),
 new WordX("happy","['hæpi]","adj 快乐的,幸福的"),
 new WordX("best","[best]","adj &adv 最好的(地)"),
 new WordX("wish","[wiʃ]","n &v  祝愿,希望,想要"),
 new WordX("second","['sekənd]","num &adj 第二(的)"),
 new WordX("idea","[ai'diə]","n 主意,想法,意见"),
 new WordX("last","[lɑ:st]","adj 最后的,刚过去的"),
 new WordX("given","name","  phr. 名字"),
 new WordX("mean","[mi:n]","v  表示...的意思,意味着"),
 new WordX("meaning","['mi:niŋ]","n 意思,意义,含义"),
 new WordX("important","[im'pɔ:tənt]","adj重要的,重大的"),
 new WordX("use","[ju:z]","v  用,使用,运用"),
 new WordX("before","[bi'fɔ:]","prep &adv 在..之前,以前"),
 new WordX("never","['nevə]","adv 从来,决不"),
 new WordX("just","[dʒʌst]","adv 刚刚,方才"),
 new WordX("third","[θə:d]","num &adj 第三的"),
 new WordX("afraid","[ə'freid]","adj 害怕的"),
 new WordX("live","[liv]","v  居住"),
 new WordX("sound","[saund]","n & v  声音,听起来"),
 new WordX("have","to","  phr. 不得不,必须"),
 new WordX("time","[taim]","n 次数"),
 new WordX("more","[mɔ:]","adv 更,更加"),
 new WordX("not...any","more","  phr. 不再"),
 new WordX("laugh","[lɑ:f]","v  & n 笑,大笑,笑声"),
 new WordX("waste","[weist]","n & v  浪费,废弃物"),
 new WordX("a","waste","of time  phr. 浪费(白费)时间"),
 new WordX("fifth","[fifθ]","num & adj 第五(的)"),
 new WordX("trip","[trip]","n & v  旅游,旅行"),
 new WordX("field","trip","  phr. 野外旅游"),
 new WordX("hometown","['hom'taun]","n 故乡,家乡"),
 new WordX("discuss","[di'skʌs]","v  讨论,议论"),
 new WordX("fish","[fiʃ]","v  钓鱼"),
 new WordX("fishing","['fiʃiŋ]","n 钓鱼"),
 new WordX("go","fishing","  phr. 去钓鱼"),
 new WordX("east","[i:st]","n & adj 东方(的),东部(的)"),
 new WordX("agree","[ə'gri:]","v  同意,赞成"),
 new WordX("boating","['bəutiŋ]","n 划船"),
 new WordX("go","boating","  phr. 去划船"),
 new WordX("maybe","['meibi]","adv 也许,大概"),
 new WordX("mountain","['mauntin]","n 山,高山"),
 new WordX("hike","[haik]","n & v  远足,徒步旅行"),
 new WordX("hiking","[haikin]","n 徒步旅行"),
 new WordX("go","hiking","  phr. 去徒步旅行"),
 new WordX("picnic","['piknik]","n 野餐"),
 new WordX("the","day","after tomorrow  phr. 后天"),
 new WordX("top","[tɔp]","n 顶部"),
 new WordX("problem","['prɔbləm]","n 问题,难题"),
 new WordX("quick","[kwik]","adj 快的,迅速的"),
 new WordX("quickly","['kwikli]","adv 快地,迅速地"),
 new WordX("start","[stɑ:t]","v  开始,着手"),
 new WordX("trip","[trip]","over   phr. (被...)绊倒"),
 new WordX("tired","['taiəd]","adj 累,疲乏"),
 new WordX("hurry","['hʌri]","v  赶快,慌忙"),
 new WordX("hurry","up","  phr. 赶快"),
 new WordX("tie","[tai]","v  捆,(系,栓)紧"),
 new WordX("die","[dai]","v  死亡"),
 new WordX("city","['siti]","n 城市"),
 new WordX("take","[teik]","v  花费(时间),消耗"),
 new WordX("eighth","[eitθ]","num 第八"),
 new WordX("salesgirl","['seilzgə:l]","n 女售货员"),
 new WordX("far","[fɑ:]","adj & adv 远的(地)"),
 new WordX("beautiful","['bju:təfəl]","adj 美丽的,漂亮的"),
 new WordX("together","[tə'geðə]","adv 一起"),
 new WordX("autumn","['ɔ:təm]","n 秋天,秋季"),
 new WordX("festival","['festəvəl]","n & adj 节日(的),喜庆(的)"),
 new WordX("ninth","[nainθ]","num &adj 第九(的)"),
 new WordX("free","[fri:]","adj 自由的,空闲的"),
 new WordX("mid-autumn","n 中秋"),
 new WordX("mooncake","n 月饼"),
 new WordX("nut","[nʌt]","n 坚果,坚果核"),
 new WordX("sweet","[swi:t]","adj 甜的,可爱的"),
 new WordX("inside","[,in'said]"," prep  在...里面"),
 new WordX("store","['in'said]","n (美)商店,大百货公司"),
 new WordX("come","over","  phr. 过来,顺便来访"),
 new WordX("thanksgiving","[,θæŋks'giviŋ]","n 感谢,感恩"),
 new WordX("Thanksgiving=Thanksgiving","Day"," phr. 感恩节"),
 new WordX("get","together"," phr. 相聚"),
 new WordX("October","[ɔk'təubə]","n. 十月"),
 new WordX("taste","[teist]","v  品尝,有...味道"),
 new WordX("pie","[pai]","n (用肉或水果做成的)馅饼"),
 new WordX("outside","['aut'said]","prep  & adv 在...外"),
 new WordX("in","the","open air   phr.在户外,在野外"),
 new WordX("harvest","['hɑ:vist]","n 收获"),
 new WordX("than","[ðæn]","conj 比....,比较...."),
 new WordX("delicious","[di'liʃəs]","adj 美味的,可口的"),
 new WordX("pumpkin","['pʌmpkin]","n 南瓜"),
 new WordX("twelfth","[twelfθ]","num &adj 第十二(的)"),
 new WordX("turkey","['tə:ki]","n 火鸡"),
 new WordX("celebrate","['selibreit]","v  庆祝"),
 new WordX("wait","[weit]","v 等,等待"),
 new WordX("feed","[fi:d]","v 喂,饲养"),
 new WordX("cow","[kau]","n 母牛,乳牛"),
 new WordX("tractor","['træktə]","n 拖拉机"),
 new WordX("taxi","['tæksi]","n 出租汽车"),
 new WordX("slow","[sləu]","adj 慢的,缓慢的"),
 new WordX("slowly","['sləuli]","adv 缓慢地"),
 new WordX("grow","[grəu]","v  种植,生长"),
 new WordX("wheat","[hwi:t]","n 小麦"),
 new WordX("country","['kʌntri]","n 乡村,郊外"),
 new WordX("hear","[hiə]","v  听见,听说"),
 new WordX("bleat","[bli:t]","v & n 羊叫(声)"),
 new WordX("agree","with","phr.同意...意见(想法)符合,一致"),
 new WordX("corn","[kɔ:n]","n (美)玉米,谷类庄稼"),
 new WordX("summer","['sʌmə]","n 夏天,夏季"),
 new WordX("winter","['wintə]","n 冬天,冬季"),
 new WordX("stop","[stɔp]","v  停止,中止"),
 new WordX("pick","[pik]","v  采摘(花,果实)"),
 new WordX("exciting","[ik'saitiŋ]","adj 令人兴奋的"),
 new WordX("town","[taun]","n 城镇"),
 new WordX("star","[stɑ:]","n 星星,恒星"),
 new WordX("until","[ən'til]","prep&pron 到...为止"),
 new WordX("till","[til]","prep&pron (直)到...为止"),
 new WordX("college","['kɔlidʒ]","n 学院,高等专科学校"),
 new WordX("farming","['fɑ:miŋ]","n 农业,务农"),
 new WordX("somebody","['sʌmbədi]","pron 某人,有人"),
 new WordX("nobody","['nəubɔdi]","pron 没有人"),
 new WordX("shall","[ʃæl]","v   (我,我们)将,会"),
 new WordX("zoo","[zu:]","n 动物园"),
 new WordX("nothing","['nʌθiŋ]","pron没有什么,没有东西"),
 new WordX("dolphin","['dɔlfin]","n 海豚"),
 new WordX("show","[ʃəu]","n&v演出,展览 给...看,出示"),
 new WordX("gate","[geit]","n 大门"),
 new WordX("land","[lænd]","n 陆地,土地"),
 new WordX("just","[dʒʌst]","adv 仅仅,只有"),
 new WordX("grass","[grɑ:s]","n 草,草地"),
 new WordX("dangerous","['deindʒərəs]","adj 危险的"),
 new WordX("panda","['pændə]","n 熊猫"),
 new WordX("lion","['laiən]","n 狮子"),
 new WordX("elephant","['elifənt]","n 象"),
 new WordX("monkey","['mʌŋki]","n 猴子"),
 new WordX("tiger","['taigə]","n 老虎"),
 new WordX("deer","[diə]","(pl.deer)  n 鹿"),
 new WordX("snake","[sneik]","n 蛇"),
 new WordX("rabbit","['ræbit]","n 兔子"),
 new WordX("duck","[dʌk]","n 鸭"),
 new WordX("fox","[fɔks]","n 狐狸"),
 new WordX("horse","[hɔ:s]","n 马"),
 new WordX("bear","[bɛə]","n 熊"),
 new WordX("cage","[keidʒ]","n 笼(子),鸟笼"),
 new WordX("should","[ʃud]v.aux","(shall的过去式)将,会,应该"),
 new WordX("forest","['fɔrist]","n 森林"),
 new WordX("feel","[fi:l]","v  觉得,感到"),
 new WordX("if","[if]","conj 假如,如果"),
 new WordX("fall","[fɔ:l]","v  落下,跌倒"),
 new WordX("climb","[klaim]","v  爬,攀登"),
 new WordX("finish","['finiʃ]","v  完成,结束"),
 new WordX("cinema","['sinimə]","n 电影院,电影"),
 new WordX("seafood","['sifu:d]","n 海鲜,海产食品"),
 new WordX("twentieth","['twentiiθ]","num 第十二"),
 new WordX("baby","['beibi]","n 婴儿,幼畜"),
 new WordX("back","[bæk]","n 背部,后面"),
 new WordX("place","[pleis]","n 地点,地方"),
 new WordX("twenty-first","[,twenti'fə:st]num","第二十一"),
 new WordX("bank","[bæŋk]","n 银行"),
 new WordX("bookshop","['bukʃɔp]","n 书店"),
 new WordX("toilet","['tɔilit]","n 厕所"),
 new WordX("museum","[mju:'ziəm]","n 博物馆"),
 new WordX("front","[frʌnt]","adj & n 前面(的),前部"),
 new WordX("in","front","of   phr. 在...前面"),
 new WordX("left","[left]","n & adj 左(的),左边(的)"),
 new WordX("right","[rait]","n & adj 右(的),右边(的)"),
 new WordX("side","[said]","n 边,面"),
 new WordX("on","the","left/right side   phr. 在左(右)边"),
 new WordX("all","the","same   phr. 仍然,还是"),
 new WordX("need","[ni:d]","v 需要,必需"),
 new WordX("ask","for","phr. 请求,询问"),
 new WordX("along","[ə'lɔŋ]","prep沿着,顺着 一起,一道"),
 new WordX("road","[rəud]","n 道路,公路"),
 new WordX("turn","[tə:n]","v  (使)转动,(使)翻动"),
 new WordX("turning","['tə:niŋ]","n 拐弯处"),
 new WordX("metre","['mi:tə]","n 公尺,米"),
 new WordX("kilometre","['kilə,mi:tə]","n 公里,千米"),
 new WordX("had","better","(do)  phr. 最好(做...)"),
 new WordX("coin","[kɔin]","n 硬币"),
 new WordX("keep","[ki:p]","v  保持,留住"),
 new WordX("as","[æz]","conj 按照,如同"),
 new WordX("moment","['məumənt]","n 片刻,瞬间"),
 new WordX("tell","[tel]","v  告述,讲述,吩咐"),
 new WordX("street","[stri:t]","n 街道"),
 new WordX("next","to","['nekst tə] phr. 相邻,靠近"),
 new WordX("around","[ə'raund]","prep  在...周围环绕着"),
 new WordX("lift","[lift]","n 电梯"),
 new WordX("up","and","down   phr. 上上下下,来来回回"),
 new WordX("busy","['bizi]","adj 忙的,繁忙的"),
 new WordX("team","[ti:m]","n 队,组"),
 new WordX("centre","['sɛntɚ]","(center ['sentə]) n 中心"),
 new WordX("popular","['pɔpjulə]","adj 大众的,流行的"),
 new WordX("soccer","['sɔkə]","n 英式足球"),
 new WordX("quite","[kwait]","adv 很,十分"),
 new WordX("month","[mʌnθ]","n 月"),
 new WordX("village","['vilidʒ]","n 村庄,乡村"),
 new WordX("strong","[strɔŋ]","adj 强壮的,坚强的"),
 new WordX("was","[wɔz]","v   be(am,is,are)的过去式"),
 new WordX("yesterday","['jestədi]","n & adv 昨天"),
 new WordX("November","[nəu'vembə]","n 十一月"),
 new WordX("ill","[il]","adj 病的"),
 new WordX("hope","[həup]","v  希望"),
 new WordX("composition","[,kɔmpə'ziʃən]n","作文作品"),
 new WordX("remember","[ri'membə]","v  记起,想起"),
 new WordX("were","[wə:]","v  动词be(are)的过去式"),
 new WordX("bit","[bit]","n 一点儿,小片"),
 new WordX("a","bit","[ə'bit] phr. 一点儿"),
 new WordX("healthy","['helθi]","adj 健康的,健壮的"),
 new WordX("grow","up","['grəu ʌp] phr. 成长,长大"),
 new WordX("visit","['vizit]","v  参观,访问,拜访"),
 new WordX("ago","[ə'gəu]","adv 以前"),
 new WordX("the","day","before yesterday  phr. 前天"),
 new WordX("enjoy","[in'dʒɔi]","v  喜欢,享受...乐趣"),
 new WordX("world","[wə:ld]","n 世界"),
 new WordX("at","the","same time   phr. 同时"),
 new WordX("a","moment","ago   phr. 刚才"),
 new WordX("just","now","  phr. 不久以前,刚才"),
 new WordX("reply","[ri'plai]","n & v  答复,回答"),
 new WordX("by","the","way   phr. 顺便说,顺便问一下"),
 new WordX("match","[mætʃ]","n 比赛,竞赛"),
 new WordX("cold","[kəuld]","adj 冷的,寒冷的"),
 new WordX("drive","[draiv]","v  驾驶"),
 new WordX("plan","[plæn]","n 计划"),
 new WordX("diary","['daiəri]","n 日记"),
 new WordX("make","telephone","calls   phr. 打电话"),
 new WordX("go","out","  phr. 外出,到外面"),
 new WordX("India","['indiə]","n 印度"),
 new WordX("went","[went]","v  动词go的过去式"),
 new WordX("rain","[rein]","v  下雨"),
 new WordX("rained"," v  动词rain的过去式"),
 new WordX("memory","['meməri]","n 记忆力,存储器"),
 new WordX("pack","[pæk]","v  打包,打行李"),
 new WordX("everything","['evriθiŋ]","pron 每件事,每样东西,一切"),
 new WordX("umbrella","[ʌm'brelə]","n 伞,雨伞"),
 new WordX("dry","[drai]","adj 干的,干燥的"),
 new WordX("newspaper","['nju:z,peipə]","n 报纸"),
 new WordX("paper","['peipə]","n 纸,报纸"),
 new WordX("morning","paper","  n 晨报"),
 new WordX("at","breakfast","  phr. 早餐时"),
 new WordX("say","goodbye","to   phr. 告别,告辞"),
 new WordX("useful","['ju:sfəl]","adj 有用的,有益的"),
 new WordX("scientist","['saiəntist]","n 科学家"),
 new WordX("invent","[in'vent]","v  发明,创造"),
 new WordX("all","the","time [,ɔ:l ðə 'taim] phr.一直,始终,老是"),
 new WordX("always","['ɔ:lweiz]","adv 总是,一直,经常"),
 new WordX("be","born","  phr. 出生于"),
 new WordX("May","[mei]","n 五月"),
 new WordX("move","[mu:v]","v  移动,搬动,搬家"),
 new WordX("understand","[,ʌndə'stænd]","v  懂得,理解"),
 new WordX("at","first"," phr. 起先,首先"),
 new WordX("most","[məust]","pron 大部分,大多数"),
 new WordX("luck","[lʌk]","n 运气,好运"),
 new WordX("April","['eiprəl]","n 四月"),
 new WordX("hate","[heit]","v  讨厌,不喜欢,憎恨"),
 new WordX("fly","[flai]","v  飞,飞行,乘飞机旅行"),
 new WordX("painting","['peintiŋ]","n 油画,水彩画"),
 new WordX("airport","['ɛəpɔ:t]","n 航空站,飞机场"),
 new WordX("Swedish","['swi:diʃ]","adj 瑞典的,瑞典人的"),
 new WordX("rock","[rɔk]","n 摇动,摇滚乐"),
 new WordX("band","[bænd]","n 乐队"),
 new WordX("concert","['kɔnsət]","n 音乐会,演奏会"),
 new WordX("give","a","concert   phr. 开音乐会"),
 new WordX("tonight","[tə'nait]","adv & n 今晚"),
 new WordX("singer","['siŋə]","n 歌唱者,歌手"),
 new WordX("journalist","['dʒə:nəlist]","n记者,新闻工作者"),
 new WordX("famous","['feiməs]","adj 有名的,著名的"),
 new WordX("Sweden","['swi:dən]","n 瑞典"),
 new WordX("song","[sɔŋ]","n 歌,歌曲,歌谣"),
 new WordX("more","than"," phr. 多过,...以上,比....更"),
 new WordX("thousand","['θauzənd]","num 千"),
 new WordX("accident","['æksidənt]","n 事故,灾难"),
 new WordX("careless","['kɛəlis]","adj 粗心的,大意的"),
 new WordX("fall","down","  phr. 倒下,跌倒,从...落下"),
 new WordX("break","[breik]","v  折断,断裂,破碎"),
 new WordX("go","on","  phr. 继续"),
 new WordX("someone","['sʌmwʌn]","pron 某人,有人"),
 new WordX("heart","[hɑ:t]","n 心(脏)"),
 new WordX("past","[pɑ:st]","n & adj 过去(的)"),
 new WordX("end","[end]","n & v  末端,终点,结束"),
 new WordX("at","the","end of   phr. 在...结尾,到...尽头"),
 new WordX("happen","['hæpən]","v  (偶然)发生,碰巧"),
 new WordX("part","[pɑ:t]","n 部分"),
 new WordX("tourist","['tu:rist]","n 旅游者,观光者"),
 new WordX("go","back","  phr. 回去"),
 new WordX("in","a","hurry   phr. 匆忙地"),
 new WordX("grape","[greip]","n 葡萄"),
 new WordX("science","['saiəns]","n (自然)科学"),
 new WordX("marry","['mæri]","v  结婚"),
 new WordX("get","married","  phr. 结婚"),
 new WordX("subject","['sʌbdʒikt]","n 题目,题材"),
 new WordX("friendship","['frendʃip]","n 友谊,友情"),
 new WordX("anyone","['eniwʌn]","pron 任何人"),
 new WordX("date","[deit]","n 日期"),
 new WordX("season","['si:zn]","n 季节"),
 new WordX("write","down","  phr. 写下,记下"),
 new WordX("January","['dʒænjueri]","n 一月"),
 new WordX("March","[mɑ:tʃ]","n 三月"),
 new WordX("June","[dʒu:n]","n 六月"),
 new WordX("July","[dʒu:'lai]","n 七月"),
 new WordX("August","[ɔ:'gʌst]","n 八月"),
 new WordX("December","[di'sembə]","n 十二月"),
 new WordX("spring","[spriŋ]","n 春天"),
 new WordX("last","[lɑ:st]","v  持续,耐久"),
 new WordX("weather","['weðə]","n 天气"),
 new WordX("warm","[wɔ:m]","adj 暖和的,热情的"),
 new WordX("come","out['kʌm","aut]phr. (花)开,发(芽),出来"),
 new WordX("heavily","['hevili]","adv大量地,猛烈地,厉害地"),
 new WordX("crop","[krɔp]","n 庄稼,收成"),
 new WordX("really","['riəli]","adv 确实,真正地"),
 new WordX("snow","[snəu]","n & v  雪,下雪"),
 new WordX("snowman","['snəu,mæn]","n 雪人"),
 new WordX("all","the","year round   phr. 一年到头"),
 new WordX("true","[tru:]","adj 真的,真实的"),
 new WordX("nearly","['niəli]","adv 将近,几乎"),
 new WordX("unlike","['ʌn'laik]","prep  不像,和...不同"),
 new WordX("opposite","['ɔpəzit]","adj 对面的,相反的"),
 new WordX("sunny","['sʌni]","adj 晴朗的,阳光充足的"),
 new WordX("cloud","[klaud]","n 云"),
 new WordX("cloudy","['klaudi]","adj 多云的,阴天的"),
 new WordX("wet","[wet]","adj 湿的"),
 new WordX("rainy","['reini]","adj 多雨的,下雨的"),
 new WordX("wind","[waind]","n 风"),
 new WordX("windy","['windi]","adj 有风的,风大的"),
 new WordX("snowy","[snəui]","adj 多雪的,降雪的"),
 new WordX("later","['leitə]","adv 以后,后来"),
 new WordX("later","on","  phr. 后来,稍后"),
 new WordX("ring","[riŋ]","v  (钟,铃等)响,摇铃"),
 new WordX("ring","up","  phr. 打电话"),
 new WordX("west","[west]","n & adj 西方、西部(的)"),
 new WordX("strange","[streindʒ]","adj 奇怪的,陌生的"),
 new WordX("sunshine","['sʌnʃain]","n 日光,阳光"),
 new WordX("melon","['melən]","n 瓜"),
 new WordX("radio","['reidiəu]","n 收音机"),
 new WordX("report","[ri'pɔ:t]","n & v  报导,报告"),
 new WordX("north","[nɔ:θ]","n & v  北方(的),北部(的)"),
 new WordX("south","[sauθ]","n & v  南方(的),南部(的)"),
 new WordX("at","times","  phr. 有时,偶尔"),
 new WordX("northeast","['nɔ:θ'i:st]","n 东北,东北部"),
 new WordX("temperature","['tempritʃə]","n 温度"),
 new WordX("above","[ə'bʌv]","prep  在...上面"),
 new WordX("daytime","['deitaim]","n 白天"),
 new WordX("below","[bi'ləu]","prep  在...下,低于"),
 new WordX("northwest","['nɔ:θ'west]","n 西北,西北部"),
 new WordX("lift","[lift]","v  (云,雾等)消散,(雨)停止"),
 new WordX("worse","[wə:s]","adj & adv ( bad,ill的比较级)更坏,更差"),
 new WordX("foggy","['fɔgi]","adj 有雾,多雾的"),
 new WordX("low","[ləu]","adj 低的,浅,矮的"),
 new WordX("birthday","['bə:θdei]","n 生日"),
 new WordX("invite","[in'vait]","v 邀请,招待"),
 new WordX("film","[film]","n 影片,电影"),
 new WordX("hold","[həuld]","v  拿,握"),
 new WordX("hold","on","['həuld ɔn] phr. (打电话时)等一等,不挂断"),
 new WordX("message","['mesidʒ]","n 消息,信息"),
 new WordX("take/leave","a","message   phr. 捎/留口信"),
 new WordX("ready","['redi]","adj 准备好的,乐意的"),
 new WordX("sandwich","['sændwitʃ]","n 三明治,夹心面包片"),
 new WordX("plate","[pleit]","n 盘子,碟子"),
 new WordX("candle","['kændl]","n 蜡烛"),
 new WordX("doorbell","['dɔ:bel]","n 门铃"),
 new WordX("present","['preznt]","n 礼物"),
 new WordX("smile","[smail]","n & v  微笑"),
 new WordX("telephone(phone","[fəun])","['telifəun] n 电话,电话机"),
 new WordX("double","['dʌbl]n","& adj两倍(的),双倍(的)"),
 new WordX("but","[bʌt]","prep  除了"),
 new WordX("take","out","  phr.  取出"),
 new WordX("the","same","as   phr. 和...相同"),
 new WordX("word","[wə:d]","n 词,单词"),
 new WordX("shout","[ʃaut]","v  呼喊,喊叫"),
 new WordX("turn","over","['tə:n ,əuvə] phr. 把...翻过来"),
 new WordX("study","['stʌdi]","n 书房"),
 new WordX("less","[les]","adj&adv ( little的比较级)较少的,较小的"),
 new WordX("less","than","  phr. 不到,少于"),
 new WordX("be","late","for   phr. 迟到"),
 new WordX("beef","[bi:f]","n 牛肉"),
 new WordX("help","yourself","to   phr. 自取,随便吃"),
 new WordX("Christmas","['krisməs]","n 圣诞节"),
 new WordX("during","['djuəriŋ]","prep  在...的期间"),
 new WordX("Spring","Festival"," n 春节"),
 new WordX("exam","[ig'zæm]","n (口语)考试"),
 new WordX("get-together","['gettə,geðə]","n 聚会"),
 new WordX("put","on","  phr. (戏剧等)上演,放(唱片等)"),
 new WordX("play","[plei]","n 剧,戏剧"),
 new WordX("shower","['ʃauə]","n 降雨,骤雨"),
 new WordX("showery","['ʃauəri]","adj 降雨的,多阵雨的"),
 new WordX("magical","['mædʒikəl]","adj 魔法(似)的"),
 new WordX("Rome","[rəum]","n 罗马(意大利首都)"),
 new WordX("Berlin","[bə:'lin]","n 柏林"),
 new WordX("Moscow","['mɔskəu]","n 莫斯科"),
 new WordX("kitchen","['kitʃin]","n 厨房"),
 new WordX("cupboard","['kʌbəd]","n 碗橱,小橱(柜)"),
 new WordX("few","[fju:]","adj 少数的,不多的"),
 new WordX("a","few","  phr. 一些,几个"),
 new WordX("salt","[sɔ:lt]","n 盐"),
 new WordX("sugar","['ʃugə]","n 糖"),
 new WordX("pepper","['pepə]","n 胡椒"),
 new WordX("oil","[ɔil]","n 油"),
 new WordX("wine","[wain]","n 酒"),
 new WordX("beer","[biə]","n 啤酒"),
 new WordX("fork","[fɔ:k]","n 叉,餐叉"),
 new WordX("spoon","[spu:n]","n 匙,调羹"),
 new WordX("chopsticks","['tʃɔpstiks]","n (常用复数)筷子"),
 new WordX("cabbage","['kæbidʒ]","n 卷心菜,洋白菜"),
 new WordX("pea","[pi:]","n 豌豆"),
 new WordX("butter","['bʌtə]","n 黄油"),
 new WordX("cheese","[tʃi:z]","n 乳酪"),
 new WordX("soup","[su:p]","n 汤"),
 new WordX("Italian","[i'tæljən]","n & adj意大利人(的),意大利语(的)"),
 new WordX("pizza","['pi:tsə]","n (意大利)烤馅饼"),
 new WordX("Indian","['indiən]","n & adj 印度人(的),印第安人(的)"),
 new WordX("kinds","of","  phr. 各种各样的"),
 new WordX("workplace","['wə:kpleis]","n 工作场所"),
 new WordX("seem","[si:m]","v  好像,似乎"),
 new WordX("even","['i:vən]","adv 甚至,更"),
 new WordX("Italy","['itəli]","n 意大利"),
 new WordX("chocolate","['tʃɔkəlit]","n 巧克力,巧克力糖"),
 new WordX("ice","[ais]","n 冰"),
 new WordX("make","[meik]","v  使...(发生)"),
 new WordX("laugh","[lɑ:f]","v  (大)笑,发笑"),
 new WordX("both","[bəuθ]","adj & pron 两个(人....)都"),
 new WordX("either","['i:ðə]","adv (用于否定句中)也(不)"),
 new WordX("either...or...","[,i:ðə'ɔ:]conj","或者...或者..."),
 new WordX("anything","['eni,θiŋ]","pron 任何事(物)"),
 new WordX("neither","['ni:ðə,nai:ðə]","adj & pron (两者)都不"),
 new WordX("nor","[nɔ:]","conj 也不"),
 new WordX("neither...nor.."," conj 既不...也不..."),
 new WordX("a","bit","(of)  phr. 少量(的),一点"),
 new WordX("without","[wi'ðaut]","prep  无,没有,不"),
 new WordX("take","a","seat [,teik ə 'si:t] phr. 坐下,就坐"),
 new WordX("waiter","['weitə]","n 服务员"),
 new WordX("madam","['mædəm]","n 女士,夫人,小姐"),
 new WordX("menu","['menju:]","n (餐厅等的)菜单"),
 new WordX("order","['ɔ:də]","n&v 订购,点菜  订购单,定购,一份菜"),
 new WordX("bill","[bil]","n 帐单,清单,纸币"),
 new WordX("be","famous","for   phr. 因...而有名的"),
 new WordX("kind","[kaind]","adj 和蔼的,友好的"),
 new WordX("lady","['leidi]","n 女士,夫人"),
 new WordX("ladies'","room","  n (妇女)公共厕所"),
 new WordX("tell","[tel]","v  说,告述,吩咐"),
 new WordX("library","['laibrəri]","n 图书馆"),
 new WordX("cross","[krɔ:s]","n 十字形(物),十字记号    v穿过,越过"),
 new WordX("crossing","['krɔ:siŋ]","n 十字路口,交叉点"),
 new WordX("across","[ə'krɔ:s]","prep  穿过,横过"),
 new WordX("miss","[mis]","v  错过"),
 new WordX("church","[tʃə:tʃ]","n 教堂,教会"),
 new WordX("cafe","[kə'fei]","n 小餐馆,咖啡厅"),
 new WordX("video","['vidiəu]","n 录像"),
 new WordX("reach","[ri:tʃ]","v  到达,抵达,达到"),
 new WordX("corner","['kɔ:nə]","n 角落,(街道)拐角"),
 new WordX("on","one's","way to   phr. 在..的途中"),
 new WordX("sick","[sik]","adj 患病的"),
 new WordX("pocket","['pɔkit]","n 衣袋"),
 new WordX("still","[stil]","adv 仍旧,更"),
 new WordX("weak","[wi:k]","adj 弱的,差的"),
 new WordX("wait","for","  phr. 等候"),
 new WordX("cut","[kʌt]","v  割,砍,切"),
 new WordX("finger","['fiŋgə]","n 手指"),
 new WordX("geography","[dʒi'ɔgrəfi]","n 地理(学)"),
 new WordX("physics","['fiziks]","n 物理(学)"),
 new WordX("history","['histəri]","n 历史(学)"),
 new WordX("key","[ki:]","n 钥匙"),
 new WordX("fix","[fiks]","v  修理,安装"),
 new WordX("suddenly","['sʌdnli]","adv 突然地"),
 new WordX("DVD","n 光碟,影碟"),
 new WordX("in","time","[in 'taim] phr. 及时"),
 new WordX("make","one's","way to   phr. 往..走去"),
 new WordX("sign","[sain]","n 标记,符号,痕迹"),
 new WordX("lost","[lɔst]","adj 迷途的,丢失的"),
 new WordX("be/get","lost","  phr. 迷失(道路)"),
 new WordX("just","then","  phr. 正在那时"),
 new WordX("first","of","all   phr. 首先,第一"),
 new WordX("main","[mein]","adj 主要的"),
 new WordX("go","wrong","[,gəu 'rɔŋ] phr. 走错路"),
 new WordX("hit","[hit]","v  打,击中,撞"),
 new WordX("noise","[nɔiz]","n 嘈杂声,响声"),
 new WordX("make","a","noise   phr. 吵闹"),
 new WordX("disturb","[dis'tə:b]","v  妨碍,打扰"),
 new WordX("passenger","['pæsindʒə]","n 乘客,旅客"),
 new WordX("get","on","['get ɔn] phr. 上(车)"),
 new WordX("get","off","['get ɔf] phr. 下来,从...下来"),
 new WordX("push","[puʃ]","v  推,挤"),
 new WordX("stand","in","line   phr. 站(在)队(里)"),
 new WordX("turn","[tə:n]","n (依次轮流的)顺序"),
 new WordX("necessary['nesə,səri]","adj","必需的,必要的"),
 new WordX("waiting","room"," n 等候室,候诊(车,机)室"),
 new WordX("jumper","['dʒʌmpə]","n 跳跃者"),
 new WordX("queue","jumper","  n 不按次序排队的人"),
 new WordX("patient","['peiʃənt]","n 病人"),
 new WordX("at","the","head of   phr.在...的最前"),
 new WordX("visitor","['vizitə]","n 参观者,访问者"),
 new WordX("live","[liv]","v  居住"),
 new WordX("knee","[ni:]","n 膝盖"),
 new WordX("hurt","[hə:t]","v  使受伤,痛"),
 new WordX("laugh","at","['lɑ:f ət] phr. 嘲笑"),
 new WordX("mistake","[mi'steik]","n 错误"),
 new WordX("quiet","['kwaiət]","adj 安静的,平静的"),
 new WordX("quietly","['kwaiətli]","adv 安静地,平静地"),
 new WordX("reading","room","  n 阅览室"),
 new WordX("alone","[ə'ləun]","adv 独自的,单独的"),
 new WordX("plastic","['plæstik]","n & adj 塑料(的)"),
 new WordX("throw","about['θrəu","ə,baut] phr.乱丢,抛散"),
 new WordX("change","[tʃeindʒ]","v  变化,变更,改变"),
 new WordX("have","a","good time   phr. 过得愉快"),
 new WordX("fact","[fækt]","n 事实,实际"),
 new WordX("in","fact","[in 'fækt] phr. 实际上"),
 new WordX("at","midnight","  phr. 在半夜"),
 new WordX("arrive","[ə'raiv]","v  到达,抵达某地"),
 new WordX("telephone","['telifəun]","v  打电话给(某人)"),
 new WordX("complain","[kəm'plein]","v  抱怨,发牢骚"),
 new WordX("quarrel","['kwɔrəl]","v  争吵"),
 new WordX("quarrel","with['kwɔrəl","wið]phr.(和某人)吵架"),
 new WordX("surprise","[sə'praiz]","n 惊奇,惊讶"),
 new WordX("police","[pə'li:s]","n 警察(局)"),
 new WordX("voice","[vɔis]","n 说话声,嗓音"),
 new WordX("enjoy","oneself[in'dʒɔi","wʌn,self]phr.过得快乐,玩得痛快"),
 new WordX("themselves","[ðəm'selvz]","pron 他们自己"),
 new WordX("care","[kɛə]","v  介意,在乎,关心"),
 new WordX("half-way"," adv 在途中,半路上"),
 new WordX("trouble","['trʌbl]","n 麻烦,烦恼"),
 new WordX("headache","['hedeik]","n 头痛"),
 new WordX("have","a","headache   phr. (患)头痛"),
 new WordX("cough","[kɔf]","v & n 咳嗽"),
 new WordX("have","a","cough   phr. (患)咳嗽"),
 new WordX("serious","['siəriəs]","adj 严重的,严肃"),
 new WordX("pain","[pein]","n 疼痛,疼"),
 new WordX("dream","[dri:m]","n & v梦,梦想 做梦,向往"),
 new WordX("worst","[wə:st]","adj 最坏的,最恶劣的"),
 new WordX("wake","[weik]","v  (使)醒来"),
 new WordX("wake","up","  phr. 醒来,唤醒"),
 new WordX("as","soon","as   conj 一...就"),
 new WordX("asleep","[ə'sli:p]","adj 睡着的,熟睡的"),
 new WordX("fall","asleep","  phr. 睡觉,入睡"),
 new WordX("plant","[plɑ:nt]","n & v  植物  种植"),
 new WordX("storm","[stɔ:m]","n 暴风雨"),
 new WordX("stop...from","phr. 阻止...做"),
 new WordX("difficult","['difikəlt]","adj 困难的,难的"),
 new WordX("pill","[pil]","n 药丸,药片"),
 new WordX("awake","[ə'weik]","adj 清醒的"),
 new WordX("be","awake","  phr. 醒着的"),
 new WordX("relax","[ri'læks]","v  放松,轻松"),
 new WordX("again","and","again phr. 再三地,一再地,反复地"),
 new WordX("angry","['æŋgri]","adj 发怒的,生气的"),
 new WordX("hard","[hɑ:d]","adj 硬的"),
 new WordX("smell","[smel]","v  闻,嗅,散发(气味)"),
 new WordX("rich","[ritʃ]","adj 有钱的,富裕的,丰富的"),
 new WordX("become","[bi'kʌm]","v  变得,变成,成为"),
 new WordX("instead","[in'sted]","adv 代替,顶替"),
 new WordX("instead","of","[in'sted əv] phr. 代替"),
 new WordX("look","over","  phr. (仔细)检查"),
 new WordX("enough","[i'nʌf]","adj 足够的,充分的"),
 new WordX("take","exercise","  phr. 做运动"),
 new WordX("fat","[fæt]","adj 肥胖的"),
 new WordX("thin","[θin]","adj 瘦的,薄的"),
 new WordX("island","['ailənd]","n 岛,岛状物"),
 new WordX("farther","['fɑ:ðə]","adj&adv (far的比较级)较远,更远"),
 new WordX("somewhere","['sʌmhwɛə]","adv 某处,在某处"),
 new WordX("land","[lænd]","v  登陆,上岸,降落"),
 new WordX("pull","[pul]","v  拉,拖,拔"),
 new WordX("out","of","  prep 从..向外,从..往外"),
 new WordX("cool","[ku:l]","adj 凉快的"),
 new WordX("anybody","['eni,bɔdi]","pron 任何人"),
 new WordX("ourselves","[,auə'selvz]","pron 我们自己"),
 new WordX("all","by","oneself   phr. 独立,单独"),
 new WordX("perhaps","[pə'hæps]","adv 也许,可能"),
 new WordX("happily","['hæpili]","adv 高兴地,快乐地"),
 new WordX("lots","of","  phr. 许许多多的"),
 new WordX("no","longer","  phr. 不再"),
 new WordX("missing","['misiŋ]","adj 丢失的,失踪的"),
 new WordX("cry","[krai]","v  哭,叫喊"),
 new WordX("get","back","['get bæk] phr. 回来,取回"),
 new WordX("too...to","phr. 太...而不能"),
 new WordX("anywhere","['enihwɛə]","adv 任何地方"),
 new WordX("solve","[sɔlv]","v  解决,解答"),
 new WordX("believe","[bi'li:v]","v  相信,认为"),
 new WordX("everybody","['evribɔdi]","pron 每人,人人"),
 new WordX("sooner","or","later   phr. 迟早"),
 new WordX("drop","[drɔp]","n & v  滴,水滴  掉下,落下"),
 new WordX("run","away","  phr. 逃跑"),
 new WordX("as","[æz]","conj 因为,由于"),
 new WordX("eat","up","  phr. 吃完,吃光"),
 new WordX("bank","[bæŋk]","n (海,河,湖的)岸,堤"),
 new WordX("circle","['sə:kl]","n 圈子,圆"),
 new WordX("yet","[jet]","adv (用于否定句)还(没)"),
 new WordX("myself","[mai'self]","pron 我自己"),
 new WordX("cousin","['kʌzn]","n 堂(表)兄弟,堂(表)姐妹"),
 new WordX("engineer","[,endʒi'niə]","n 工程师"),
 new WordX("cancer","['kænsə]","n 癌症"),
 new WordX("care","[kɛə]","n 小心,照料,保护"),
 new WordX("take","care","of   phr. 照顾,照料,注意"),
 new WordX("sad","[sæd]","adj 难过的,悲哀的"),
 new WordX("death","[deθ]","n 死,死亡"),
 new WordX("page","[peidʒ]","n (书的)页"),
 new WordX("palace","['pælis]","n 宫,宫殿"),
 new WordX("the","Summer","Palace   n 颐和园"),
 new WordX("herself","[hə:'self]","pron 她自己"),
 new WordX("turn","on['tə:n","ɔn]phr.打开(电灯,收音机,煤气,自来水)"),
 new WordX("while","[hwail]","n 一会儿"),
 new WordX("after","a","while   phr. 过了一会儿"),
 new WordX("turn","off","['tə:n ɔf]phr.关(电灯,收音机,煤气,自来水等)"),
 new WordX("any","more","  phr. 再,更"),
 new WordX("make","faces","  phr. 做鬼脸,做苦脸"),
 new WordX("whole","[həul]","adj 全部的"),
 new WordX("wonderful","['wʌndəfəl]","adj极好的,精彩的"),
 new WordX("have","a","cold   phr. (患)感冒"),
 new WordX("once","[wʌns]","adv 曾经,以前"),
 new WordX("himself","[him'self]","pron 他自己"),
 new WordX("tooth","[tu:θ]","n 牙齿"),
 new WordX("kill","[kil]","v  杀死,弄死"),
 new WordX("teach","oneself"," phr. 自学"),
 new WordX("fall","off","['fɔ:l ɔf] phr. (从...)掉下"),
 new WordX("clever","['klevə]","adj 聪明的,机灵的"),
 new WordX("yourselves","[jɔ:'sɛlvz]","pron 你们自己"),
 new WordX("find","out","['faind aut] phr. 找出,查出"),
 new WordX("piano","[pi'ænəu]","n 钢琴"),
 new WordX("moonlight","['mu:n,lait]","n & adj 月光(的)"),
 new WordX("poor","[puə]","adj 贫穷的,可怜的"),
 new WordX("knock","[nɔk]","v  敲,击"),
 new WordX("knock","at","  phr. 敲(门,窗等)"),
 new WordX("dim","[dim]","adj 微暗的,昏暗的"),
 new WordX("pardon","['pɑ:dn]","v  原谅(某人),宽恕"),
 new WordX("to","one's","surprise   phr. 令(某人)惊讶"),
 new WordX("blind","[blaind]","adj 瞎的,盲的"),
 new WordX("shine","[ʃain]","v  照亮,发亮"),
 new WordX("bright","[brait]","adj 明亮的,晴朗的"),
 new WordX("brightly","['braitli]","adv 明亮地,闪亮地"),
 new WordX("through","[θru:]","prep  通过,穿过,经过"),
 new WordX("look","up","['luk ʌp] phr. 向上看,抬头看"),
 new WordX("silently","['sailəntli]","adv 寂静地,沉默地"),
 new WordX("come","along","come along phr. 来,随同"),
 new WordX("return","[ri'tə:n]","v  回来,归还"),
 new WordX("cookie","['kuki]","n 小甜饼"),
 new WordX("leave...behind","phr. 把...遗留在(留下)"),
 new WordX("hold","a","sports meeting   phr. 举行运动会"),
 new WordX("race","[reis]","n 赛跑"),
 new WordX("100-metre","race","  phr. 100米赛跑"),
 new WordX("win","[win]","v  获胜,赢"),
 new WordX("high","jump","  n 跳高"),
 new WordX("long","jump","  n 跳远"),
 new WordX("neck","[nek]","n 颈,脖子"),
 new WordX("active","['æktiv]","adj 积极的"),
 new WordX("take","an","active part in   phr.积极参加"),
 new WordX("relay","[ri'lei]","n 接力,赛跑"),
 new WordX("starting/finishing","line"," phr. 起点/终点线"),
 new WordX("runner","['rʌnə]","n 赛跑的人"),
 new WordX("loud","[laud]","adj 大声的,响亮的"),
 new WordX("loudly","['laudli]","adv 大声地,高声地"),
 new WordX("lap","[læp]","n (竞赛场的)一圈"),
 new WordX("pass","on","['pɑ:s ɔn] phr. 传递,转移到..."),
 new WordX("stick","[stik]","n 棒,棍"),
 new WordX("catch","up","with   phr. 赶上"),
 new WordX("neck","and","neck   phr. (竞赛等)并驾齐驱"),
 new WordX("as...as","conj 与...一样"),
 new WordX("a","moment","later  phr. 片刻之后"),
 new WordX("go","on","doing sth  phr. 继续做(某事)"),
 new WordX("fall","behind"," phr. 落在...后面,输给别人"),
 new WordX("winner","['winə]","n 获胜者"),
 new WordX("well","done","  phr. 做得好"),
 new WordX("congratulation[kən,grætju'leiʃən]","n","(常用复数)祝贺,庆贺"),
 new WordX("not","as/so...as"," conj 与...不一样"),
 new WordX("rather","['rɑ:ðə]","adv 相当"),
 new WordX("result","[ri'zʌlt]","n 结果"),
 new WordX("dance","[dɑ:ns]","v  跳舞"),
 new WordX("headmaster","['hed'mɑ:stə]","n 校长"),
 new WordX("take","turns","[,teik 'tə:nz] phr. 轮流"),
 new WordX("do","one's","best   phr. 尽最大努力,尽力"),
 new WordX("person","['pə:sn]","n 人"),
 new WordX("speed","[spi:d]","n 迅速,速度"),
 new WordX("thought","[θɔ:t]","n 思考,思想,想法"),
 new WordX("technology","[tek'nɔlədʒi]","n 技术,工艺学"),
 new WordX("best-seller","n 畅销货(书)"),
 new WordX("interested","['intəristid]","adj 感兴趣的"),
 new WordX("be","interested","in   phr. 对..感兴趣"),
 new WordX("Washington","['wɔʃiŋtən]","n 华盛顿"),
 new WordX("future","['fju:tʃə]","n 将来,未来"),
 new WordX("in","the","future   phr. 将来"),
 new WordX("large","[lɑ:dʒ]","adj 大的,(数量)多的"),
 new WordX("spend","[spend]","v  花(时间,钱),度过"),
 new WordX("unusual","[ʌn'ju:ʒuəl]adj","不寻常的,非凡的"),
 new WordX("in","the","end   phr. 最后"),
 new WordX("work","out","  phr. 算出,制定出"),
 new WordX("software","['sɔftwɛə]","n (电脑)软件"),
 new WordX("university","[,ju:ni'və:siti]","n 综合性大学"),
 new WordX("develop","[di'veləp]","v  发展,研制,开发"),
 new WordX("BASIC","['beisik]","n (电脑)初学者通用符号指令码"),
 new WordX("microcomputer","['maikrəukəm'pju:tə]","n 微型计算机"),
 new WordX("Microsoft","['maikrəusɔft]","n 微软公司"),
 new WordX("tool","[tu:l]","n 工具"),
 new WordX("personal","['pə:sənl]","adj 私人的,个人的"),
 new WordX("improve","[im'pru:v]","v  提高,改善"),
 new WordX("golf","[gɔlf]","n 高尔夫球"),
 new WordX("bridge","[bridʒ]","n 桥牌"),
 new WordX("pleased","[pli:zd]","adj 高兴的,愉快的"),
 new WordX("T-shirt","['ti:ʃə:t]","n 短袖无领汗杉,T恤(杉)"),
 new WordX("disease","[di'zi:z]","n 疾病"),
 new WordX("million","['miljən]","n 百万,百万元"),
 new WordX("decide","[di'said]","v  决定,决心"),
 new WordX("billion","['biljən]","n 十亿"),
 new WordX("lucky","['lʌki]","adj 幸运的,侥幸的"),
 new WordX("unlucky","[ʌn'lʌki]","adj 不走运的,不幸的"),
 new WordX("size","[saiz]","n 尺寸,大小"),
 new WordX("almost","['ɔ:lməust]","adv 几乎,差不多"),
 new WordX("speaker","['spi:kə]","n 演讲者,说话者"),
 new WordX("joke","[dʒəuk]","n 笑话,玩笑"),
 new WordX("play","a","joke on   phr. 戏弄人,对某人恶作剧"),
 new WordX("lose","[lu:z]","v  丢失,失去,迷失(方向)"),
 new WordX("hide","[haid]","v  躲藏"),
 new WordX("check","[tʃek]","v  检查,核对"),
 new WordX("lie","[lai]","v  躺,平躺"),
 new WordX("deaf","[def]","adj 聋的"),
 new WordX("painter","['peintə]","n 画家"),
 new WordX("get","on","well with  phr. 与...相处融洽"),
 new WordX("neighbour","['neibə]","n 邻居"),
 new WordX("ever","['evə]","adv 曾经"),
 new WordX("upstairs","['ʌp'stɛəz]","adj & adv (在)楼上,(往)楼上"),
 new WordX("take","off","  phr. 脱下(衣,帽,鞋等)"),
 new WordX("boot","[bu:t]","n 长统鞋"),
 new WordX("downstairs","[,daun'stɛəz]","adj & adv(在)楼下,(往)楼下"),
 new WordX("bang","[bæŋ]","v  猛敲,猛撞,砰砰作响"),
 new WordX("be","angry","with   phr. 对(某人)发脾气"),
 new WordX("usual","['ju:ʒuəl]","adj 通常的,平常的"),
 new WordX("as","usual","[əz 'ju:ʒuəl] phr. 像平常一样"),
 new WordX("sound","[saund]","n 声音"),
 new WordX("PE"," n 体育"),
 new WordX("chemistry","['kemistri]","n 化学"),
 new WordX("sweep","[swi:p]","v  扫,扫地"),
 new WordX("choose","[tʃu:z]","v  选择,挑选"),
 new WordX("truck","[trʌk]","n 卡车"),
 new WordX("seller","['selə]","n 卖者,售货员"),
 new WordX("biology","[bai'ɔlədʒi]","n 生物(学)"),
 new WordX("be","fed","up with   phr. 厌倦"),
 new WordX("knock","on","  phr. 敲(门,窗等)"),
 new WordX("refuse","[ri'fju:z]","v  拒绝"),
 new WordX("politely","[pə'laitli]","adv 有礼貌地"),
 new WordX("pair","[pɛə]","n 一对,一双"),
 new WordX("a","pair","of   phr. 一对,一双"),
 new WordX("scissors","['sizəz]","n (复数)剪刀"),
 new WordX("racket","['rækit]","n (网球,羽毛球等的)球拍"),
 new WordX("review","[ri'vju:]","v  复习(功课等)"),
 new WordX("Russian","['rʌʃən]","n&adj俄国的,俄国人(的), 俄语(的)"),
 new WordX("novel","['nɔvəl]","n (长篇)小说"),
 new WordX("wallet","['wɔlit]","n 钱夹,皮夹"),
 new WordX("ground","[graund]","n 地面,土地"),
 new WordX("cause","[kɔ:z]","v  引起"),
 new WordX("suddenly","['sʌdnli]","adv 突然地"),
 new WordX("luckily","['lʌkili]","adv 好运地,幸运地"),
 new WordX("gatekeeper","['geit,ki:pə]","n 看门人,门卫"),
 new WordX("mention","['menʃən]","v  提到,说起"),
 new WordX("crow","[krəu]","v  拥挤"),
 new WordX("imagine","[i'mædʒin]","v  设想,想像"),
 new WordX("while","[hwail]","conj 当..时候,和..同时"),
 new WordX("repair","[ri'pɛə]","v  修理,修补"),
 new WordX("steer","[stiə]","n & v  驾驶,掌舵"),
 new WordX("steering","wheel","  n 驾驶盘"),
 new WordX("dive","[daiv]","v  潜入(水中),跳水"),
 new WordX("diver","['daivə]","n 潜入水中的人,潜水员"),
 new WordX("at","once","  phr. 立刻,马上"),
 new WordX("mouth-to-mouth","['mauθtə'mauθ]","adj(人工呼吸)口对口的"),
 new WordX("breathe","[bri:ð]","v  呼吸"),
 new WordX("come","to","oneself  phr. 苏醒,恢复知觉"),
 new WordX("rob","[rɔb]","v  抢劫"),
 new WordX("hard-working","adj 辛勤工作的,用功的"),
 new WordX("art","[ɑ:t]","n 艺术,艺术品"),
 new WordX("at","the","moment  phr. 此刻"),
 new WordX("Titanic","[tai'tænik]","n 泰坦尼克(船名)"),
 new WordX("set","[set]","v  使开始,安置"),
 new WordX("set","off","['set ɔf] phr. 出发,动身,起初"),
 new WordX("pleasant","['pleznt]","adj 愉快的,快乐的"),
 new WordX("iceberg","['aisbə:g]","n 冰山"),
 new WordX("here","and","there   phr. 到处,处处"),
 new WordX("on","watch","  phr. 值班,守望"),
 new WordX("look","out","  phr. 留神,注意"),
 new WordX("in","front","  phr. 前方,正对面"),
 new WordX("hole","[həul]","n 洞,孔,坑"),
 new WordX("sink","[siŋk]","v  下沉,沉没"),
 new WordX("life","[laif]","n 生命,生活"),
 new WordX("lifeboat","['laifbəut]","n 救生船(艇)"),
 new WordX("make","room","for   phr. 给..腾出地方"),
 new WordX("take","one's","place phr.坐某人的座位,代替某人的职位"),
 new WordX("thankful","['θæŋkfəl]","adj 感激的,感谢的"),
 new WordX("Boston","['bɔstən]","n 波士顿(美国马萨诸塞州的首府)"),
 new WordX("war","[wɔ:]","n 战争 "),
 new WordX("information","[,infə'meiʃən]","n 信息,情报"),
 new WordX("noisy","['nɔizi]","adj 喧闹的,嘈杂的"),
 new WordX("penguin","['peŋgwin]","n 企鹅"),
 new WordX("pink","[piŋk]","adj 粉红色的,桃红色的"),
 new WordX("shellfish","['ʃelfiʃ]","n 贝类,甲壳虫"),
 new WordX("lay","[lei]","v  下蛋,产蛋 "),
 new WordX("pretty","['priti]","adj 漂亮的,美丽的"),
 new WordX("toe","[təu]","n 脚趾  "),
 new WordX("rub","[rʌb]","v  磨,擦"),
 new WordX("human","['hju:mən]","n & adj 人(的),人类(的)"),
 new WordX("CD","player","  phr. 激光唱机"),
 new WordX("several","['sevərəl]","adj & pron 几个；若干"),
 new WordX("shelf","[ʃelf]","(pl. shelves[ʃelvz])  n 架子；搁板"),
 new WordX("already","[ɔ:l'redi]","adv 已经"),
 new WordX("used","to","  phr. 过去常常"),
 new WordX("on","[ɔn]","prep  关于"),
 new WordX("knowledge","['nɔlidʒ]","n 知识；学问"),
 new WordX("yard","[jɑ:d]","n 院子"),
 new WordX("schoolyard","['sku:ljɑ:d]","n 校园"),
 new WordX("put","(sth)","down   phr.把某物放下来"),
 new WordX("step","[step]","n & v  脚步；走；踏入；踩"),
 new WordX("librarian","[lai'brɛəriən]","n 图书管理员"),
 new WordX("probably","['prɔbəbli]","adv 很可能；大概"),
 new WordX("pay","(paid[peid]",",pay的过去式和过去分词)[pei]v 付钱；支付"),
 new WordX("pay","for","['pei fə(r)] phr. 付钱；支付"),
 new WordX("sadly","['sædli]","adv 难过地；悲哀地 "),
 new WordX("come","up","with    phr. 找到；提出（答案，办法） "),
 new WordX("mark","[mɑ:k]","n 记号；标记；痕迹    "),
 new WordX("bookmark","['buk,mɑ:k]","n 书签"),
 new WordX("think","of","  phr. 想起   "),
 new WordX("encourage","[in'kʌridʒ]","v  鼓励"),
 new WordX("get…back"," phr. 退还；送 回去；取 回"),
 new WordX("pick…up"," phr. 拾起；捡起"),
 new WordX("once","[wʌns]","adv 一次"),
 new WordX("abroad","[ə'brɔ:d]","adv 到国外；在国外"),
 new WordX("copy","['kɔpi]","v  抄写；"),
 new WordX("as","[æz]","prep  作为"),
 new WordX("screen","[skri:n]","n 屏幕"),
 new WordX("spoil","[spɔil](spoilt[spɔilt],spoil的过去式与过去分词)","v 糟蹋"),
 new WordX("surf","[sə:f]","v  冲浪"),
 new WordX("surfing","['sə:fiŋ]","n 冲浪运动"),
 new WordX("surfer","['sə:fə]","n 冲浪者"),
 new WordX("wave","[weiv]","n 浪；波浪"),
 new WordX("beach","[bi:tʃ]","n 海（河、湖）滩"),
 new WordX("have","a","try   phr. 尝试；努力；射击"),
 new WordX("twice","[twais]","adv 两次；两倍"),
 new WordX("none","[nʌn]","pron 一个人也没有；没有任何东 西"),
 new WordX("water-ski","['wɔ:təski:]","v  做滑水运动"),
 new WordX("canoe","[kə'nu:]","v  乘独木舟"),
 new WordX("describe","[di'skraib]","v  描写；叙述"),
 new WordX("all","over","  phr. 遍及"),
 new WordX("especially","[is'peʃəli]","adv 特别；尤其"),
 new WordX("attract","[ə'trækt]","v  吸引"),
 new WordX("large","numbers","of   phr. 许多"),
 new WordX("no","matter","  phr. 不论"),
 new WordX("so-called","['səu'kɔ:ld]","adj 所谓的"),
 new WordX("possible","['pɔsəbl]","adj 可能的"),
 new WordX("both…and…","phr.   ...和...都"),
 new WordX("give","up","  phr. 放弃"),
 new WordX("since","[sins]","adv & conj 此后;自..以来"),
 new WordX("ever","since","  phr. 从那时起；此后一直"),
 new WordX("although","[ɔ:l'ðəu]","conj 虽然；尽管"),
 new WordX("fit","[fit]","adj & v  健康的；适合的；（使）适 合"),
 new WordX("prize","[praiz]","n 奖品；奖赏"),
 new WordX("competition","[,kɔmpi'tiʃən]","n 比赛；竞争"),
 new WordX("event","[i'vent]","n 大事；事件"),
 new WordX("Olympic","[əu'limpik]","adj 奥林匹克的"),
 new WordX("the","Olympic","Games   phr. 奥林匹克运动会"),
 new WordX("such","[sʌtʃ]","adj 这样的"),
 new WordX("fail","[feil]","v  失败；不及格"),
 new WordX("business","['biznis]","n 商业；生意；事务"),
 new WordX("so","far","  phr. 到目前为止"),
 new WordX("cross","[krɔ:s]","v  越过；穿过"),
 new WordX("channel","['tʃænl]","n 海峡；航道；频道；波段"),
 new WordX("come","true","[,kʌm 'tru:] phr. 实现"),
 new WordX("mainland","['meinlənd]","n 大陆；本土"),
 new WordX("slow","[sləu]","v  放慢；减速"),
 new WordX("slow","down","  phr. 减缓；减速"),
 new WordX("journey","['dʒə:ni]","n 旅程；旅行；路程"),
 new WordX("among","[ə'mʌŋ]","prep  在……当中"),
 new WordX("proud","[praud]","adj 自豪的；骄傲的"),
 new WordX("be","proud","of   phr. 以……自豪（兴奋）"),
 new WordX("speak","highly","of   phr. 称赞"),
 new WordX("not","only…but","also  phr. 不但……而且"),
 new WordX("pride","[praid]","n 自豪；骄傲"),
 new WordX("unless","[ən'les]","conj 除非；如果不"),
 new WordX("shot","[ʃɔt]","n 尝试；努力；射击"),
 new WordX("truth","[tru:θ]","n 真理，真相，事实"),
 new WordX("pour","[pɔ:]","v  倒；灌；倾泻"),
 new WordX("waste","[weist]","adj & n 废弃的；无用的；垃圾；废物"),
 new WordX("dirty","['də:ti]","adj 脏的"),
 new WordX("be","afraid","of   phr. 害怕"),
 new WordX("member","['membə]","n 成员"),
 new WordX("join","[dʒɔin]","v  加入；参加"),
 new WordX("environment","[in'vaiərənmənt]","n 环境"),
 new WordX("harm","[hɑ:m]","v  损害；伤害"),
 new WordX("rubbish","['rʌbiʃ]","n 垃圾；废物"),
 new WordX("collect","[kə'lekt]","v  收集；搜集"),
 new WordX("whenever","[hwen'evə]","conj&adv无论什么时候;随时"),
 new WordX("produce","[prə'dju:s]","v  产生；生产；制造"),
 new WordX("wherever","[hwɛər'evə]","conj & adv 无论在（到）哪里；在任何地方"),
 new WordX("neighbourhood","['neibəhud]","n. 四邻；街坊；邻近"),
 new WordX("litter","['litə]","n & v  垃圾，废物；乱丢杂物"),
 new WordX("onto","['ɔntu:]","prep  在…上面；到…上面"),
 new WordX("public","['pʌblik]","adj 公共的；公众的"),
 new WordX("cut","down","['kʌt daun] phr. 砍倒"),
 new WordX("protect","[prə'tekt]","v  保护"),
 new WordX("tidy","['taidi]","adj 整洁的；整齐的"),
 new WordX("dustbin","['dʌstbin]","n 垃圾箱"),
 new WordX("recycle","[ri:'saikl]","v  再循环；回收再用"),
 new WordX("contribution","[,kɔntri'bju:ʃən]","n 贡献"),
 new WordX("make","a","contribution to   phr. 贡献给；捐赠"),
 new WordX("suppose","[sə'pəuz]","v  猜想"),
 new WordX("riddle","['ridl]","n 谜语"),
 new WordX("do","well","in   phr. 在……某方面干得好"),
 new WordX("nearby","['niəbai]","adv 附近"),
 new WordX("headmaster","['hed'mɑ:stə]","n （英)中小学校长"),
 new WordX("mount","[maunt]","n  …山；…峰"),
 new WordX("as","soon","as possible   phr. 尽可能早地；尽快"),
 new WordX("except","[ik'sept]","prep  除…之外"),
 new WordX("province","['prɔvins]","n 省"),
 new WordX("enjoyable","[in'dʒɔiəbl]","adj 愉快的；有趣的"),
 new WordX("rush","[rʌʃ]","v  冲；奔跑"),
 new WordX("rail","[reil]","n 轨道；铁路"),
 new WordX("railway","['reilwei]","n （英）铁路"),
 new WordX("lively","['laivli]","adj 热闹的；有生气的"),
 new WordX("all","kinds","of   phr. 各种各样的"),
 new WordX("comfortable","['kʌmfətəbl]","adj 舒适的；舒服的"),
 new WordX("keep","doing","something   phr. 一直做某事"),
 new WordX("scenery","['si:nəri]","n 风景；景色"),
 new WordX("offer","['ɔ:fə]","v  & n 拿出；提供"),
 new WordX("magazine","[,mægə'zi:n]","n 杂志"),
 new WordX("practise","['præktis]","v  实践；练习"),
 new WordX("moving","['mu:viŋ]","adj. 活动的；移动的；动的人"),
 new WordX("click","[klik]","n & v  咔哒声;发出咔哒声"),
 new WordX("pity","['piti]","n 遗憾的事，可惜的事"),
 new WordX("score","[skɔ:]","n & v  （比赛）得分"),
 new WordX("own","[əun]","adj 自己的"),
 new WordX("least","[li:st]","adj 最小的；最少的"),
 new WordX("kid","[kid]","n （口语）小伙子"),
 new WordX("scuba","['skju:bə]","n 水肺（潜水者用的水下呼吸器）"),
 new WordX("Internet","['intə,net]","n 因特网，互联网络"),
 new WordX("search","[sə:tʃ]","v  搜查，搜索"),
 new WordX("double","['dʌbl]","adj & v  双重的，双倍的"),
 new WordX("icon","['aikɔn]","n 图象符号，图标"),
 new WordX("type","[taip]","v  (用打字机或电脑)打字"),
 new WordX("press","[pres]","v  按，压"),
 new WordX("enter","['entə]","v  进入"),
 new WordX("button","['bʌtn]","n 按钮，纽扣"),
 new WordX("capital","['kæpitl]","n 首都"),
 new WordX("population","[,pɔpju'leiʃən]","n 人口，人数"),
 new WordX("ridge","[ridʒ]","n 山脉"),
 new WordX("tomb","[tu:m]","n 坟墓"),
 new WordX("whether","['hweðə]","conj 是否"),
 new WordX("edge","[edʒ]","n 边，边缘"),
 new WordX("rim","[rim]","n 边，缘"),
 new WordX("cool","[ku:l]","adj （俚语）了不起"),
 new WordX("cost","[kɔst]","v  价钱为，花费（金钱、时间等）"),
 new WordX("one-way","['wʌn,wei]","adj 单程的，单行的"),
 new WordX("flight","[flait]","n 航班，飞行"),
 new WordX("book","[buk]","v  预定（戏票、车票等）"),
 new WordX("instruction","[in'strʌkʃən]","n 说明，须知"),
 new WordX("straight","[streit]","adv 一直地"),
 new WordX("go","straight","along    phr. 沿着…一直往前走"),
 new WordX("whom","[hu:m]","pron 谁，哪个人（who的宾格）"),
 new WordX("think","about","  phr. 考虑"),
 new WordX("chance","[tʃɑ:ns]","n 机会"),
 new WordX("coral","['kɔrəl]","n 珊瑚"),
 new WordX("reef","[ri:f]","n 岩礁"),
 new WordX("coral","reef","  n 珊瑚礁"),
 new WordX("sound","[saund]","v  听起来"),
 new WordX("brochure","[brəu'ʃjuə]","n 小册子"),
 new WordX("pool","[pu:l]","n 水池，水坑"),
 new WordX("outdoor","['autdɔ:]","adj 户外的，野外的"),
 new WordX("badly","['bædli]","adv 严重地，恶劣地"),
 new WordX("allow","[ə'lau]","v  允许，准许"),
 new WordX("deep","[di:p]","adj 深的"),
 new WordX("explore","[iks'plɔ:]","v  探测，探险"),
 new WordX("explorer","[iks'plɔ:rə]","n 探测者，探险者"),
 new WordX("undersea","['ʌndə'si:]","adj 海底的"),
 new WordX("amaze","[ə'meiz]","v  使…大为惊讶，使惊"),
 new WordX("be","amazed","at   phr. 对…感到惊讶"),
 new WordX("however","[hau'evə]","conj 然而，可是"),
 new WordX("colourful","['kʌləfəl]","adj 颜色艳丽的"),
 new WordX("dead","[ded]","adj 死的"),
 new WordX("society","[sə'saiəti]","n 社会"),
 new WordX("since","[sins]","conj 由于，既然"),
 new WordX("cover","['kʌvə]","v  覆盖"),
 new WordX("earth","[ə:θ]","n 陆地，大地，地球"),
 new WordX("clean","up","['kli:n ʌp] phr. 清除，收拾干净"),
 new WordX("ocean","['əuʃən]","n 海洋，大洋"),
 new WordX("pollute","[pə'lu:t]","v  污染，弄脏"),
 new WordX("group","[gru:p]","n 组，群，团队"),
 new WordX("terrific","[tə'rifik]","adj （口语）很棒的，极好的"),
 new WordX("as","long","as   phr. 长达…"),
 new WordX("sometime","['sʌmtaim]","adv （未来的）某时"),
 new WordX("deal","[di:l]","n （口语）协议，交易"),
 new WordX("shark","['ʃɑ:k]","n 鲨鱼"),
 new WordX("on","earth","[ɔn 'ə:θ] phr. 在地球上"),
 new WordX("alike","[ə'laik]","adj 相似的，相像的"),
 new WordX("attack","[ə'tæk]","n & v  攻击，袭击"),
 new WordX("Africa","['æfrikə]","n 非洲"),
 new WordX("South","Africa","  n 南非"),
 new WordX("watchtower","['wɔtʃ'tauə]","n 监视塔，瞭望塔"),
 new WordX("warn","[wɔ:n]","v  警告，提醒"),
 new WordX("appear","[ə'piə]","v  出现，露面"),
 new WordX("able","['eibl]","adj 有能力的，能干的"),
 new WordX("be","able","to   phr. 能，会"),
 new WordX("neatly","['ni:tli]","adv 整洁地"),
 new WordX("own","[əun]","v  拥有，所有"),
 new WordX("spirit","['spirit]","n 精神"),
 new WordX("inventor","[in'ventə]","n 发明者，创造者"),
 new WordX("try","out","['trai aut] phr. 实验，尝试"),
 new WordX("pupil","['pju:pl]","n 小学生，学生"),
 new WordX("build","[bild]","v  建立，建造，建设"),
 new WordX("at","the","age of   phr. 在…岁时"),
 new WordX("print","[print]","v  印刷，印制"),
 new WordX("track","[træk]","n (火车等的)轨道，跑道"),
 new WordX("frighten","['fraitən]","v  惊恐，吓唬"),
 new WordX("frightened","['fraitnd]","adj 受惊的，害怕的"),
 new WordX("rush","out","['rʌʃ aut] phr. 冲出去"),
 new WordX("safety","['seifti]","n 安全"),
 new WordX("telegraph","['teligrɑf]","n 电报"),
 new WordX("invention","[in'venʃən]","n 发明，创造"),
 new WordX("open","up","['əupən ʌp] phr. 开设，开业，开放"),
 new WordX("lifetime","['laiftaim]","n 一生，终生"),
 new WordX("graduate","['grædjueit]","v  毕业"),
 new WordX("turn","down","['tə:n daun] phr. 关小，调低"),
 new WordX("healthily","['helθili]","adv 健康地"),
 new WordX("clearly","['kliəli]","adv 清楚地"),
 new WordX("frustrate","[frʌs'treit]","v  使沮丧，使失败"),
 new WordX("frustrated","[frʌs'treitid]","adj 感到灰心丧气的"),
 new WordX("wonder","['wʌndə]","v 惊奇，惊讶,（对...）感到怀疑"),
 new WordX("worth","[wə:θ]","adj 有…的价值，值得"),
 new WordX("confidence","['kɔnfidəns]","n 信心，自信"),
 new WordX("merry","['meri]","adj 愉快的；欢乐的"),
 new WordX("decorate","['dekəreit]","v  装饰，修饰"),
 new WordX("put","up","['put ʌp] phr. 挂起，举起"),
 new WordX("angel","['eindʒəl]","n 天使，守护神"),
 new WordX("circle","['sə:kl]","v  & n 环绕，绕行    圆，圈子"),
 new WordX("eve","[i:v]","n （节日或重大事件发生的）前夕"),
 new WordX("stocking","['stɔkiŋ]","n 长统袜"),
 new WordX("pet","[pet]","n 宠爱的动物"),
 new WordX("as","well","[əz 'wel] adv 又，同样地"),
 new WordX("kind-hearted"," adj 好心的"),
 new WordX("chimney","['tʃimni]","n 烟囱，烟筒"),
 new WordX("single","['siŋgl]","adj 单个的，只有一个的"),
 new WordX("base","[beis]","v  以…作根据，基于"),
 new WordX("base","on","  phr. 以…（为）根据"),
 new WordX("real","['ri:əl]","adj 真正的，真实的"),
 new WordX("Turkey","['tə:ki]","n 土耳其"),
 new WordX("shy","[ʃai]","adj 害羞的，腼腆的"),
 new WordX("hang","[hæŋ]","v  吊着，悬挂"),
 new WordX("fireplace","['faiəpleis]","n 壁炉"),
 new WordX("dry","[drai]","v  把…弄干，晒干"),
 new WordX("though","[ðəu]","conj 虽然…，尽管…"),
 new WordX("even","though","  conj 即使…"),
 new WordX("generosity","[,dʒenə'rɔsiti]","n 慷慨，豁达"),
 new WordX("live","on","  phr. 继续存在，继续活着"),
 new WordX("relative","['relətiv]","n 亲属，亲人"),
 new WordX("greet","[gri:t]","v  问候，向（人）打招呼"),
 new WordX("hug","[hʌg]","n 拥抱，紧抱"),
 new WordX("western","['westən]","adj 西方的，西部的"),
 new WordX("traditional","[trə'diʃənəl]","adj 传统的，惯例的"),
 new WordX("once","upon","a time   phr. 从前，很早以前"),
 new WordX("special","['speʃəl]","adj 特别的，特殊的"),
 new WordX("at","last","[ət 'lɑ:st] phr. 终于，最后"),
 new WordX("owner","['əunə]","n 拥有者，所有者"),
 new WordX("barn","[bɑ:n]","n 谷仓，堆物房；马房，牛舍"),
 new WordX("give","birth","to   phr. 生（孩子）"),
 new WordX("shepherd","['ʃepəd]","n 牧羊人"),
 new WordX("be","made","in   phr. 在…生产或制造"),
 new WordX("be","made","of   phr. 由…组成，由…构成"),
 new WordX("brush","[brʌʃ]","n 刷子，毛笔，画笔"),
 new WordX("writing","brush","  n 毛笔"),
 new WordX("bamboo","[bæm'bu:]","n 竹子"),
 new WordX("be","used","for   phr. 用于"),
 new WordX("pan","[pæn]","n 平底锅"),
 new WordX("jacket","['dʒækit]","n夹克衫"),
 new WordX("metal","['metl]","n 金属"),
 new WordX("stamp","[stæmp]","n 邮票"),
 new WordX("wool","[wul]","n 羊毛，绒线"),
 new WordX("wood","[wud]","n 木头，木材"),
 new WordX("lock","[lɔk]","n & v  锁；上锁"),
 new WordX("store","[stɔ:]","v  储藏，存储"),
 new WordX("widely","['waidli]","adv 广泛地，广阔地"),
 new WordX("Britain","['britən]","n 英国，不列颠"),
 new WordX("set","[set]","n 装置，设备"),
 new WordX("a","TV","set   phr. 一台电视"),
 new WordX("Germany","['dʒə:məni]","n 德国"),
 new WordX("Frenchman","['frentʃmən]","n 法国人"),
 new WordX("traveller","['trævlə]","n 旅行者"),
 new WordX("cotton","['kɔtn]","n 棉花"),
 new WordX("silk","[silk]","n （蚕）丝"),
 new WordX("camera","['kæmərə]","n 照相机"),
 new WordX("digital","['didʒitəl]","adj 数字似的"),
 new WordX("ordinary","['ɔ:dnri]","adj 普通的，通常的"),
 new WordX("aeroplane","['ɛərəplein]","n 飞机"),
 new WordX("satellite","['sætəlait]","n 卫星"),
 new WordX("rocket","['rɔkit]","n 火箭"),
 new WordX("on","show","[ɔn 'ʃəu] phr. 展出"),
 new WordX("dinosaur","['dainəsɔ:]","n 恐龙"),
 new WordX("display","[di'splei]","n 陈列"),
 new WordX("on","display","[ɔn dis'plei] phr. 陈列，展览"),
 new WordX("natural","['nætʃərəl]","adj 自然界的，天然的"),
 new WordX("guide","[gaid]","n & v  向导，导游者；指导，引导"),
 new WordX("underground","['ʌndəgraund]","adj 地下的"),
 new WordX("fossil","['fɔsl]","n 化石"),
 new WordX("desert","['dezət]","n 沙漠"),
 new WordX("Gobi","Desert","  n 戈壁沙漠"),
 new WordX("human","being","  n 人"),
 new WordX("disappear","[,disə'piə]","v  消失"),
 new WordX("disappearance","[,disə'piərəns]","n 消失"),
 new WordX("discover","[dis'kʌvə]","v  发现，发觉"),
 new WordX("feather","['feðə]","n 羽毛"),
 new WordX("found","[faund]","v  成立，建立"),
 new WordX("entrance","['entrəns]","n 入口，进口，入场"),
 new WordX("exit","['eksit]","n 出口"),
 new WordX("fragile","['frædʒil]","adj 易碎的"),
 new WordX("park","[pɑ:k]","v  （将车）停放"),
 new WordX("parking","['pɑ:kiŋ]","n 停车（处）"),
 new WordX("danger","['deindʒə]","n 危险"),
 new WordX("pause","[pɔ:z]","v  & n 中止，暂停"),
 new WordX("teapot","['ti:pɔt]","n 茶壶"),
 new WordX("bowl","[bəul]","n 碗"),
 new WordX("serve","[sə:v]","v  上（酒、菜等），开（饭）；服务"),
 new WordX("fill","[fil]","v  装满，填充"),
 new WordX("be","filled","with   phr. 用…充满"),
 new WordX("object","['ɔbdʒikt]","n 物体"),
 new WordX("dig","[dig]","v  挖，掘"),
 new WordX("make","sure","[,meik 'ʃuə(r)] phr.确保,确认,查明"),
 new WordX("so","that","  conj 以便，以致"),
 new WordX("hear","of","  phr. 听说"),
 new WordX("run","away","['rʌn ə,wei] phr.流失,逃跑，逃走"),
 new WordX("drought","[draut]","n 旱灾，干旱"),
 new WordX("drop","[drɔp]","n 滴，水滴"),
 new WordX("soil","[sɔil]","n 土壤，土地"),
 new WordX("directly","[di'rektli]","adv 直接地"),
 new WordX("leaf","[li:f]","n 叶子，树木、草的叶子"),
 new WordX("in","this","way   phr. 用这种方法"),
 new WordX("flood","[flʌd]","n & v  洪水，水灾；淹没，泛滥"),
 new WordX("prevent","[pri'vent]","v  防止，阻止"),
 new WordX("northern","['nɔ:ðən]","adj 北部的，北方的"),
 new WordX("wide","[waid]","adj 宽的"),
 new WordX("blow(blew[blu:],blow的过去式;blown[bləun],blow的过去分词)","[bləu]","v  吹"),
 new WordX("sand","[sænd]","n 沙，沙子"),
 new WordX("towards","[tə'wɔ:dz]","prep  向，朝"),
 new WordX("farmland","['fɑ:mlænd]","n 农田"),
 new WordX("point","[pɔint]","v  指，指向…"),
 new WordX("point","to","['pɔint tə] phr. 指向…"),
 new WordX("far","away","  phr. 很远，遥远"),
 new WordX("thanks","to","['θæŋks tə] phr. 由于，幸亏"),
 new WordX("the","more","the better   phr.越多越好"),
 new WordX("correct","[kə'rekt]","adj 改正"),
 new WordX("hand","in","  phr. 交上来"),
 new WordX("more","or","less   phr. 多少有点，或多或少"),
 new WordX("grand","[grænd]","adj 豪华的，庄重的，雄伟的"),
 new WordX("hall","[hɔ:l]","n 大厅，会堂，会馆"),
 new WordX("notice","['nəutis]","n 通告，布告"),
 new WordX("audience","['ɔ:diəns]","n 听众"),
 new WordX("slipper","['slipə]","n (常用复数)拖鞋,便鞋"),
 new WordX("height","[hait]","n 高度"),
 new WordX("beeper","['bi:pə]","n 袖珍无线电传呼机,电话呼叫机"),
 new WordX("someday","['sʌmdei]","adv （今后）有一天"),
 new WordX("printer","['printə]","n 打印机"),
 new WordX("print","[print]","v  打印"),
 new WordX("document","['dɔkjumənt]","n 公文，文件"),
 new WordX("connect","[kə'nekt]","v  连接，相连，联系"),
 new WordX("modem","['məudem]","n 调制解调器"),
 new WordX("provide","[prə'vaid]","v  提供"),
 new WordX("monitor","['mɔnitə]","n 显示器"),
 new WordX("point","at","  phr. 指示，指向"),
 new WordX("universe","['ju:nivə:s]","n 宇宙"),
 new WordX("man-made","['mænmeid]","adj 人造的，人工的"),
 new WordX("satellite","['sætəlait]","n 卫星"),
 new WordX("space","[speis]","n 空间，太空"),
 new WordX("spaceship","['speisʃip]","n 宇宙飞船"),
 new WordX("send","[send]","v  送，寄，派（遣）"),
 new WordX("send","up","  phr. 发射，把…往上送"),
 new WordX("receive","[ri'si:v]","v  接受，收到，得到"),
 new WordX("shut","[ʃʌt]","v  关（门等）"),
 new WordX("shut","down","['ʃʌt daun] phr. 把…关上"),
 new WordX("woolen","['wulin]","adj 羊毛的，毛织的"),
 new WordX("impossible","[im'pɔsəbl]","adj 不可能的"),
 new WordX("mind","[maind]","n & v  思想，想法；关心，介意"),
 new WordX("set","one's","mind to do   phr. 一心想做…"),
 new WordX("put","off","  phr. 推迟，拖延"),
 new WordX("worm","['put","ɔf] n 虫，蠕虫"),
 new WordX("activity","[æk'tiviti]","n 活动"),
 new WordX("increase","[in'kri:s]","v  增加，增长"),
 new WordX("if","[if]","conj 是否"),
 new WordX("hour","after","hour    phr.  一小时又一小时,连续地"),
 new WordX("multiply","['mʌltiplai]","v  （将…）乘…"),
 new WordX("multiply…by…"," phr.  …乘以…"),
 new WordX("challenge","['tʃælindʒ]","n 挑战"),
 new WordX("beginning","[bi'giniŋ]","n 开始，开端"),
 new WordX("at","the","beginning of   phr. …起初，开始"),
 new WordX("square","[skwɛə]","n 平方，（方形的）广场"),
 new WordX("hardly","['hɑ:dli]","adv 几乎不"),
 new WordX("more","and","more   phr. 越来越…"),
 new WordX("prefer","[pri'fə:]","v  宁愿（选择），更喜欢"),
 new WordX("prefer","to","  phr. 宁愿（选择），更喜欢"),
 new WordX("rather","than"," phr.宁可,是..而不是"),
 new WordX("used","[ju:st]","adj 用过的，半旧的"),
 new WordX("beg","[beg]","v  恳求，乞求"),
 new WordX("beg","one's","pardon   phr. 请原谅，对不起"),
 new WordX("worth","[wə:θ]","adj 值得..的，有..的价值"),
 new WordX("secondhand","['sekənd'hænd]","adj 二手的，用过的"),
 new WordX("diagram","['daiəgræm]","n 图表"),
 new WordX("discussion","[di'skʌʃən]","n 讨论"),
 new WordX("be","busy","doing   phr. 忙于做…"),
 new WordX("chart","[tʃɑ:t]","n 图表"),
 new WordX("download","['daunləud]","v 下载"),
 new WordX("path","[pɑ:θ]","n 路线，去路"),
 new WordX("Brazil","[brə'zil]","n 巴西"),
 new WordX("excited","[ik'saitid]","adj 兴奋的，激动的"),
 new WordX("be","excited","about   phr. 对…感到兴奋"),
 new WordX("leather","['leðə]","n 皮革"),
 new WordX("wear","out","['wɛər aut] phr. 把…穿旧，磨坏"),
 new WordX("yen","[jen]","n 元，日元"),
 new WordX("try","on","['trai ɔn]phr. 试穿（衣服,鞋）,试戴（帽子）"),
 new WordX("online","[,ɔn'lain]","adj & adv 在线，上网"),
 new WordX("ad","[æd]","n 广告"),
 new WordX("Canon","['kænən]","n 佳能（照相机牌名）"),
 new WordX("shape","[ʃeip]","n 形状，外形"),
 new WordX("decision","[di'siʒən]","n 决定"),
 new WordX("make","a","decision   phr. 作出决定"),
 new WordX("screen","[skri:n]","n 屏幕"),
 new WordX("form","[fɔ:m]","n 表格"),
 new WordX("credit","['kredit]","n 信用"),
 new WordX("credit","card","  n 信用卡"),
 new WordX("successfully","[sək'sesfəli]","adv 圆满地,顺利地,成功地"),
 new WordX("interest","['intərist]","n 兴趣"),
 new WordX("a","place","of interest   phr. 名胜"),
 new WordX("forever","[fə'revə]","adv 永远，总是"),
 new WordX("lend(lent[lent],lend的过去式和过去分词)","[lend]","v把…借给，借给"),
 new WordX("go","over","['gəu ,əuvə(r)] phr. 过一遍，仔细检查"),
 new WordX("make","a","mistake [,meik ə mis 'teik] phr. 犯错误"),
 new WordX("suit","[su:t]","n 一套衣服"),
 new WordX("drop","off","['drɔp ɔf] phr. 放下（某物），下车"),
 new WordX("opera","['ɔpərə]","n 歌剧"),
 new WordX("Peking","opera","  n 京剧"),
 new WordX("the","Great","Hall of the people   n 人民大会堂"),
 new WordX("huge","[hju:dʒ]","adj 巨大的"),
 new WordX("the","Palace","Museum  n 故宫博物院"),
 new WordX("rewarding","[ri'wɔ:diŋ]","adj 值得作的"),
 new WordX("grateful","['greitfəl]","adj 感激的，感谢的"),
 new WordX("wag","[wæg]","v  摆动，摇动（尾巴等）"),
 new WordX("tail","[teil]","n 尾巴，尾部"),
 new WordX("lonely","['ləunli]","adj 孤独的，寂寞的"),
 new WordX("success","[sək'ses]","n 成就，成功"),
 new WordX("Scotland","['skɔtlənd]","n 苏格兰"),
 new WordX("make","up","one's mind   phr. 下决心"),
 new WordX("vet","[vet]","n （口语）兽医"),
 new WordX("mostly","['məustli]","adv 主要地，大部分"),
 new WordX("heal","[hi:l]","v  使（伤、病）痊愈"),
 new WordX("pig","[pig]","n 猪"),
 new WordX("education","[,edjukeiʃn]","n 教育，培养"),
 new WordX("countryside","['kʌntri'said]","n 乡下，农村"),
 new WordX("treat","[tri:t]","v  治疗，对待"),
 new WordX("before","long","[bi ,fɔ: 'lɔŋ] phr. 不久以后"),
 new WordX("regard","[ri'gɑ:d]","v  看待，当作"),
 new WordX("regard…","as","  phr. 把…当作，当作"),
 new WordX("exactly","[ig'zæktli]","adv 准确地，严格地"),
 new WordX("keep","[ki:p]","v  饲养，照顾"),
 new WordX("experience","[iks'piəriəns]","n 经验，体验"),
 new WordX("injection","[in'dʒekʃən]","n 注射，打针"),
 new WordX("painful","['peinfəl]","adj 疼痛的，痛苦的"),
 new WordX("earthquake","['ə:θkweik]","n 地震"),
 new WordX("rock","[rɔk]","v  震动，摇动"),
 new WordX("as","if","[əz 'if] conj 好像,似乎"),
 new WordX("at","sea","[ət 'si:] phr. 在大海上"),
 new WordX("story","['stɔ:ri]","n （房屋的）层"),
 new WordX("two-story","n 两层"),
 new WordX("grab","[græb]","v  抓取…，夺取"),
 new WordX("crash","[kræʃ]","v  坠落，冲撞"),
 new WordX("mobile","['məubil]","adj 可移动的"),
 new WordX("mobile","phone","  n 可移动电话"),
 new WordX("at","all","[ət 'ɔ:l] phr. （用否定句）一点也不"),
 new WordX("least","[li:st]","n 最少，最小"),
 new WordX("at","least","  phr. 至少，起码"),
 new WordX("beat","[bi:t]","v  打败，敲打"),
 new WordX("goal","[gəul]","n （足球）球门，得分"),
 new WordX("by","the","time   phr. 到…的时候"),
 new WordX("check-out","['tʃek,aut]","n（购货时的）结帐台,收银台"),
 new WordX("realize","['riəlaiz]","v  察觉，领悟，了解"),
 new WordX("train","[trein]","v  训练，培养"),
 new WordX("training","['treiniŋ]","n 训练，培养"),
 new WordX("captain","['kæptin]","n （足球队等）队长"),
 new WordX("deserve","[di'zə:v]","v  应得，值得…"),
 new WordX("confident","['kɔnfidənt]","adj 有自信的，确信的"),
 new WordX("striker","['straikə]","n （足球）前锋"),
 new WordX("midfield","['midfi:ld]","n 中场"),
 new WordX("midfield","player","  n 中场球员"),
 new WordX("excellent","['eksələnt]","adj 极好的，优秀的"),
 new WordX("shot","[ʃɔt]","n （球赛中）击，射门，投篮，发射"),
 new WordX("nervous","['nə:vəs]","adj 紧张不安的"),
 new WordX("lazy","['leizi]","adj 懒惰的"),
 new WordX("carry","on","['kæri ɔn] phr. 坚持下去，继续下去"),
 new WordX("final","['fainl]","adj 最后的"),
 new WordX("amazing","[ə'meiziŋ]","adj 令人惊奇的"),
 new WordX("be","pleased","with   phr. 对…感到满意"),
 new WordX("performance","[pə'fɔ:məns]","n 演出，成果，成绩"),
 new WordX("teamwork","['ti:mwə:k]","n 合作，协同工作"),
 new WordX("baseball","['beis,bɔ:l]","n 棒球"),
 new WordX("never","mind","[,nevə 'maind] phr. 没关系"),
 new WordX("boring","['bɔ:riŋ]","adj 令人厌烦的"),
 new WordX("spill(spilt[spilt],spill的过去式和过去分词)","[spil]","v  溢出，溅出，洒出"),
 new WordX("from","now","on [frəm 'nau ɔn] phr. 从现在起，今后"),
 new WordX("rule","[ru:l]","n 规则，规定"),
 new WordX("against","[ə'genst]","prep  与…对抗，对着"),
 new WordX("expect","[iks'pekt]","v  期望，预期"),
 new WordX("rough","[rʌf]","adj 粗鲁的，激烈的"),
 new WordX("necklace","['neklis]","n 项链"),
 new WordX("steal(stole[stəul],steal的过去式;stolen['stəulən]steal的过去分词)","[sti:l]","v  偷，窃取"),
 new WordX("hands","up","  phr. 举手"),
 new WordX("shoot(shot[ʃɔt],shoot的过去式和过去分词)[ʃu:t]","v"," 射击，射死"),
 new WordX("detective","[di'tektiv]","n 侦探"),
 new WordX("inspector","[in'spektə]","n 警官，监督员"),
 new WordX("thief","[θi:f]","n 贼"),
 new WordX("notice","['nəutis]","v  注意，通知"),
 new WordX("robber","['rɔbə]","n 强盗，盗贼"),
 new WordX("come","down","['kʌm daun] phr. 下来，落"),
 new WordX("escape","[i'skeip]"," n & v 逃亡，逃走，逃避"),
 new WordX("victim","['viktim]","n 受害者，受骗者"),
 new WordX("conversation","[,kɔnvə'seiʃən]","n 会话，谈话"),
 new WordX("robbery","['rɔbəri]"," n 抢劫案，抢劫"),
 new WordX("description","[di'skripʃən]"," n 描述，描写"),
 new WordX("excuse[ik'skju:s]","n","借口，托词"),
 new WordX("steep","[sti:p]","adj 陡峭的，险峻的"),
 new WordX("British","['britiʃ]"," adj 英国人的"),
 new WordX("misty","['misti]","adj 有雾的，雾大的"),
 new WordX("mist","[mist]"," n 雾"),
 new WordX("wonder","['wʌndə]"," v 惊奇，惊讶（对. . . . ）感到怀"),
 new WordX("club","[klʌb]"," n 俱乐部，社团"),
 new WordX("expert","[ek'spə:t]","n 专家，内行"),
 new WordX("trap","[træp]","v 使…陷入困境，设陷阱捕捉"),
 new WordX("tent","[tent]","n 帐篷"),
 new WordX("freeze","[fri:z]","(froze [frəuz], frozen ['frəuzn])  v 结冰，凝结"),
 new WordX("alive","[ə'laiv]"," adj 活着的"),
 new WordX("anytime","['enitaim]"," adv 在任何时候"),
 new WordX("progress","['prəuɡres]","v 进步，提高，前进"),
 new WordX("self-respect","['selfri'spekt]"," n 自尊，自重"),
 new WordX("essential","[i'senʃəl]"," adj 本质的，主要的，必需的")
 ]
